"""Business logic and background services."""

from .ai_services import (
    FaceDetectorService,
    OCRService,
    PlateDetectorService,
    YOLOWorldService,
)
from .alert_dedup import AlertDeduplicationService, DedupResult, build_dedup_key
from .alert_engine import AlertRuleEngine, EvaluationResult, TriggeredRule, get_alert_engine
from .analyzer_facade import (
    AnalyzerServiceFacade,
    get_analyzer_facade,
    reset_analyzer_facade,
)
from .audit import (
    AuditService,
    audit_service,
    get_db_audit_service,
    reset_db_audit_service,
)
from .background_evaluator import (
    BackgroundEvaluator,
    get_background_evaluator,
    reset_background_evaluator,
)
from .baseline import BaselineService, get_baseline_service, reset_baseline_service
from .batch_aggregator import BatchAggregator
from .cache_service import (
    DEFAULT_TTL,
    LONG_TTL,
    SHORT_TTL,
    CacheKeys,
    CacheService,
    get_cache_service,
    reset_cache_service,
)
from .circuit_breaker import (
    CircuitBreaker,
    CircuitBreakerConfig,
    CircuitBreakerError,
    CircuitBreakerOpenError,
    CircuitBreakerRegistry,
    CircuitState,
    get_circuit_breaker,
    reset_circuit_breaker_registry,
)
from .cleanup_service import CleanupService, CleanupStats
from .clip_generator import (
    ClipGenerationError,
    ClipGenerator,
    get_clip_generator,
    reset_clip_generator,
)
from .clip_loader import load_clip_model
from .context_enricher import (
    BaselineContext,
    ContextEnricher,
    CrossCameraActivity,
    EnrichedContext,
    RecentEvent,
    ZoneContext,
    get_context_enricher,
    reset_context_enricher,
)
from .cost_tracker import (
    BudgetStatus,
    CloudPricing,
    CostModel,
    CostTracker,
    DailyUsage,
    UsageRecord,
    get_cost_tracker,
    reset_cost_tracker,
)
from .dedupe import (
    DedupeService,
    HashResult,
    compute_file_hash,
    compute_file_hash_async,
    get_dedupe_service,
    reset_dedupe_service,
)
from .degradation_manager import (
    DegradationManager,
    DegradationMode,
    DegradationServiceStatus,
    QueuedJob,
    ServiceHealth,
    get_degradation_manager,
    reset_degradation_manager,
)
from .detector_client import DetectorClient, DetectorUnavailableError
from .enrichment_pipeline import (
    BoundingBox,
    DetectionInput,
    EnrichmentPipeline,
    EnrichmentResult,
    FaceResult,
    LicensePlateResult,
    get_enrichment_pipeline,
    reset_enrichment_pipeline,
)
from .evaluation_queue import (
    EvaluationQueue,
    get_evaluation_queue,
    reset_evaluation_queue,
)
from .event_broadcaster import EventBroadcaster, get_broadcaster, stop_broadcaster
from .event_service import (
    EventService,
    get_event_service,
    reset_event_service,
)
from .face_detector import (
    FaceDetection,
    PersonDetection,
    detect_faces,
    is_person_class,
)
from .file_service import (
    DEFAULT_DELETION_DELAY_SECONDS,
    FILE_DELETION_QUEUE,
    FileDeletionJob,
    FileService,
    get_file_service,
    reset_file_service,
)
from .file_watcher import (
    MIN_IMAGE_FILE_SIZE,
    FileWatcher,
    is_image_file,
    is_valid_image,
)
from .florence_extractor import (
    EnvironmentContext,
    FlorenceExtractor,
    PersonAttributes,
    SceneAnalysis,
    VehicleAttributes,
    get_florence_extractor,
    reset_florence_extractor,
)
from .florence_loader import load_florence_model
from .gpu_config_service import GpuAssignment, GpuConfigService
from .gpu_detection_service import (
    AI_SERVICE_VRAM_REQUIREMENTS_MB,
    GpuDetectionService,
    GpuDevice,
    GpuUtilization,
    get_gpu_detection_service,
    reset_gpu_detection_service,
)
from .gpu_monitor import GPUMonitor
from .household_matcher import (
    HouseholdMatch,
    HouseholdMatcher,
    get_household_matcher,
    reset_household_matcher,
)
from .job_status import (
    DEFAULT_COMPLETED_JOB_TTL,
    JOB_STATUS_KEY_PREFIX,
    JOB_STATUS_LIST_KEY,
    JOBS_ACTIVE_KEY,
    JobMetadata,
    JobState,
    JobStatusService,
    get_job_status_service,
    reset_job_status_service,
)
from .job_timeout_service import (
    DEFAULT_JOB_TIMEOUT,
    DEFAULT_MAX_RETRY_ATTEMPTS,
    JOB_TIMEOUTS,
    JobTimeoutService,
    TimeoutConfig,
    TimeoutResult,
    get_job_timeout_service,
    reset_job_timeout_service,
)
from .job_tracker import (
    PROGRESS_THROTTLE_INCREMENT,
    BroadcastCallback,
    JobCompletedData,
    JobEventType,
    JobFailedData,
    JobInfo,
    JobProgressData,
    JobStatus,
    JobTracker,
    get_job_tracker,
    reset_job_tracker,
)
from .managed_service import (
    ManagedService,
    ServiceConfig,
    ServiceRegistry,
    get_service_registry,
    reset_service_registry,
)
from .model_zoo import (
    MODEL_ZOO,
    PERSON_CLASS,
    VEHICLE_CLASSES,
    ModelConfig,
    ModelManager,
    get_available_models,
    get_enabled_models,
    get_model_config,
    get_model_manager,
    get_model_zoo,
    get_total_vram_if_loaded,
    reset_model_manager,
    reset_model_zoo,
)
from .monitoring_stack_validator import (
    AlertingRulesStatus,
    GrafanaStatus,
    MonitoringStackHealth,
    MonitoringStackValidator,
    PrometheusStatus,
    ScrapeTarget,
    ScrapeTargetHealth,
)
from .nemotron_analyzer import NemotronAnalyzer
from .notification import (
    DeliveryResult,
    NotificationChannel,
    NotificationDelivery,
    NotificationService,
    get_notification_service,
    reset_notification_service,
)
from .ocr_service import (
    PlateText,
    clean_plate_text,
    read_plates,
    read_single_plate,
)
from .partition_manager import (
    PartitionConfig,
    PartitionInfo,
    PartitionManager,
)
from .pg_notify_listener import (
    PgNotifyChannel,
    PgNotifyListener,
    PgNotifyPayload,
    get_pg_notify_listener,
    stop_pg_notify_listener,
)
from .pipeline_quality_audit_service import (
    PipelineQualityAuditService,
    get_audit_service,
    reset_audit_service,
)
from .plate_detector import (
    PlateDetection,
    VehicleDetection,
    detect_plates,
    is_vehicle_class,
)
from .reid_service import (
    DEFAULT_SIMILARITY_THRESHOLD,
    EMBEDDING_DIMENSION,
    EMBEDDING_TTL_SECONDS,
    EntityEmbedding,
    EntityMatch,
    ReIdentificationService,
    cosine_similarity,
    get_reid_service,
    reset_reid_service,
)
from .retry_handler import (
    DLQStats,
    JobFailure,
    RetryConfig,
    RetryHandler,
    RetryResult,
    get_retry_handler,
    reset_retry_handler,
)
from .scene_change_detector import (
    SceneChangeDetector,
    SceneChangeResult,
    get_scene_change_detector,
    reset_scene_change_detector,
)
from .scene_change_service import (
    SceneChangeService,
    classify_scene_change_type,
)
from .search import (
    SearchFilters,
    SearchResponse,
    SearchResult,
    refresh_event_search_vector,
    search_events,
    update_event_object_types,
)
from .severity import (
    SEVERITY_COLORS,
    SEVERITY_PRIORITY,
    SeverityDefinition,
    SeverityService,
    get_severity_color,
    get_severity_priority,
    get_severity_service,
    reset_severity_service,
    severity_from_string,
    severity_gt,
    severity_gte,
    severity_lt,
    severity_lte,
)
from .thumbnail_generator import ThumbnailGenerator
from .track_service import (
    DEFAULT_MAX_TRAJECTORY_POINTS,
    DEFAULT_TRACK_RETENTION_HOURS,
    TrackService,
    configure_track_service,
    get_track_service,
    reset_track_service,
)
from .transcode_cache import (
    CacheEntry,
    CacheStats,
    TranscodeCache,
    get_transcode_cache,
    reset_transcode_cache,
)
from .worker_supervisor import (
    SupervisorConfig,
    WorkerInfo,
    WorkerStatus,
    WorkerSupervisor,
    get_worker_supervisor,
    reset_worker_supervisor,
)
from .zone_service import (
    bbox_center,
    detection_in_zone,
    get_highest_priority_zone,
    get_zones_for_detection,
    point_in_zone,
    zones_to_context,
)

__all__ = [  # noqa: RUF022  # Intentionally organized by category
    # Constants
    "AI_SERVICE_VRAM_REQUIREMENTS_MB",
    "DEFAULT_JOB_TIMEOUT",
    "DEFAULT_MAX_RETRY_ATTEMPTS",
    "DEFAULT_SIMILARITY_THRESHOLD",
    "DEFAULT_TTL",
    "EMBEDDING_DIMENSION",
    "EMBEDDING_TTL_SECONDS",
    "LONG_TTL",
    "MIN_IMAGE_FILE_SIZE",
    "MODEL_ZOO",
    "PROGRESS_THROTTLE_INCREMENT",
    "DEFAULT_COMPLETED_JOB_TTL",
    "JOB_STATUS_KEY_PREFIX",
    "JOB_STATUS_LIST_KEY",
    "JOB_TIMEOUTS",
    "JOBS_ACTIVE_KEY",
    "PERSON_CLASS",
    "SEVERITY_COLORS",
    "SEVERITY_PRIORITY",
    "SHORT_TTL",
    "VEHICLE_CLASSES",
    "DEFAULT_DELETION_DELAY_SECONDS",
    "FILE_DELETION_QUEUE",
    "DEFAULT_MAX_TRAJECTORY_POINTS",
    "DEFAULT_TRACK_RETENTION_HOURS",
    # Classes - AI Services
    "FaceDetectorService",
    "OCRService",
    "PlateDetectorService",
    "YOLOWorldService",
    # Classes - Facades
    "AnalyzerServiceFacade",
    # Classes
    "PipelineQualityAuditService",
    "AlertDeduplicationService",
    "AlertRuleEngine",
    "AuditService",
    "BackgroundEvaluator",
    "BaselineContext",
    "BaselineService",
    "BatchAggregator",
    "BoundingBox",
    "BroadcastCallback",
    "CacheKeys",
    "CacheService",
    "CircuitBreaker",
    "CircuitBreakerConfig",
    "CircuitBreakerError",
    "CircuitBreakerOpenError",
    "CircuitBreakerRegistry",
    "CircuitState",
    "ManagedService",
    "ServiceConfig",
    "ServiceRegistry",
    "CleanupService",
    "CleanupStats",
    "ClipGenerationError",
    "ClipGenerator",
    "ContextEnricher",
    "CostModel",
    "CostTracker",
    "CrossCameraActivity",
    "CloudPricing",
    "BudgetStatus",
    "DailyUsage",
    "UsageRecord",
    "DLQStats",
    "DedupResult",
    "DedupeService",
    "HashResult",
    "DegradationManager",
    "DegradationMode",
    "DeliveryResult",
    "DetectionInput",
    "DetectorClient",
    "DetectorUnavailableError",
    "EnrichedContext",
    "EnrichmentPipeline",
    "EnrichmentResult",
    "EntityEmbedding",
    "EntityMatch",
    "EnvironmentContext",
    "EvaluationQueue",
    "EvaluationResult",
    "EventBroadcaster",
    "EventService",
    "FileDeletionJob",
    "FileService",
    "FaceDetection",
    "FaceResult",
    "FileWatcher",
    "FlorenceExtractor",
    "GpuAssignment",
    "GpuConfigService",
    "GpuDetectionService",
    "GpuDevice",
    "GpuUtilization",
    "GPUMonitor",
    "HouseholdMatch",
    "HouseholdMatcher",
    "JobCompletedData",
    "JobEventType",
    "JobFailedData",
    "JobFailure",
    "JobInfo",
    "JobMetadata",
    "JobProgressData",
    "JobState",
    "JobStatus",
    "JobStatusService",
    "JobTimeoutService",
    "JobTracker",
    "LicensePlateResult",
    "ModelConfig",
    "ModelManager",
    "NemotronAnalyzer",
    "NotificationChannel",
    "NotificationDelivery",
    "NotificationService",
    "PartitionConfig",
    "PartitionInfo",
    "PartitionManager",
    "PgNotifyChannel",
    "PgNotifyListener",
    "PgNotifyPayload",
    "PersonAttributes",
    "PersonDetection",
    "PlateDetection",
    "PlateText",
    "QueuedJob",
    "RecentEvent",
    "ReIdentificationService",
    "RetryConfig",
    "RetryHandler",
    "RetryResult",
    "TimeoutConfig",
    "TimeoutResult",
    "SceneAnalysis",
    "SceneChangeDetector",
    "SceneChangeResult",
    "SceneChangeService",
    "SearchFilters",
    "SearchResponse",
    "SearchResult",
    "ServiceHealth",
    "DegradationServiceStatus",
    "SeverityDefinition",
    "SeverityService",
    "ThumbnailGenerator",
    # Track Service
    "TrackService",
    # Transcode Cache
    "CacheEntry",
    "CacheStats",
    "TranscodeCache",
    "TriggeredRule",
    "VehicleAttributes",
    "VehicleDetection",
    "ZoneContext",
    # Monitoring Stack Validator
    "AlertingRulesStatus",
    "GrafanaStatus",
    "MonitoringStackHealth",
    "MonitoringStackValidator",
    "PrometheusStatus",
    "ScrapeTarget",
    "ScrapeTargetHealth",
    # Worker Supervisor
    "SupervisorConfig",
    "WorkerInfo",
    "WorkerStatus",
    "WorkerSupervisor",
    # Functions
    "audit_service",
    "bbox_center",
    "classify_scene_change_type",
    "configure_track_service",
    "get_audit_service",
    "build_dedup_key",
    "clean_plate_text",
    "compute_file_hash",
    "compute_file_hash_async",
    "cosine_similarity",
    "detect_faces",
    "detect_plates",
    "detection_in_zone",
    "get_alert_engine",
    "get_analyzer_facade",
    "get_available_models",
    "get_background_evaluator",
    "get_baseline_service",
    "get_broadcaster",
    "get_cache_service",
    "get_circuit_breaker",
    "get_clip_generator",
    "get_context_enricher",
    "get_cost_tracker",
    "get_db_audit_service",
    "get_dedupe_service",
    "get_degradation_manager",
    "get_enabled_models",
    "get_enrichment_pipeline",
    "get_evaluation_queue",
    "get_event_service",
    "get_file_service",
    "get_florence_extractor",
    "get_gpu_detection_service",
    "get_household_matcher",
    "get_highest_priority_zone",
    "get_job_status_service",
    "get_job_timeout_service",
    "get_job_tracker",
    "get_model_config",
    "get_model_manager",
    "get_model_zoo",
    "get_notification_service",
    "get_pg_notify_listener",
    "get_reid_service",
    "get_retry_handler",
    "get_scene_change_detector",
    "get_severity_color",
    "get_severity_priority",
    "get_severity_service",
    "get_total_vram_if_loaded",
    "get_transcode_cache",
    "get_track_service",
    "get_worker_supervisor",
    "get_zones_for_detection",
    "is_image_file",
    "is_person_class",
    "is_valid_image",
    "is_vehicle_class",
    "load_clip_model",
    "load_florence_model",
    "point_in_zone",
    "read_plates",
    "read_single_plate",
    "refresh_event_search_vector",
    "reset_analyzer_facade",
    "reset_background_evaluator",
    "reset_baseline_service",
    "reset_cache_service",
    "reset_circuit_breaker_registry",
    "get_service_registry",
    "reset_service_registry",
    "reset_clip_generator",
    "reset_context_enricher",
    "reset_cost_tracker",
    "reset_db_audit_service",
    "reset_dedupe_service",
    "reset_degradation_manager",
    "reset_enrichment_pipeline",
    "reset_evaluation_queue",
    "reset_event_service",
    "reset_file_service",
    "reset_florence_extractor",
    "reset_gpu_detection_service",
    "reset_household_matcher",
    "reset_job_status_service",
    "reset_job_timeout_service",
    "reset_job_tracker",
    "reset_model_manager",
    "reset_model_zoo",
    "reset_notification_service",
    "reset_reid_service",
    "reset_retry_handler",
    "reset_scene_change_detector",
    "reset_audit_service",
    "reset_severity_service",
    "reset_transcode_cache",
    "reset_track_service",
    "reset_worker_supervisor",
    "search_events",
    "severity_from_string",
    "severity_gt",
    "severity_gte",
    "severity_lt",
    "severity_lte",
    "stop_broadcaster",
    "stop_pg_notify_listener",
    "update_event_object_types",
    "zones_to_context",
]
