"""GPU configuration service for docker-compose override file generation.

This module provides the GpuConfigService class that generates docker-compose
GPU override files from configuration, enabling multi-GPU support for AI services.

Key Features:
- Generate docker-compose.gpu-override.yml for GPU device assignment
- Generate gpu-assignments.yml for human-readable inspection
- Support for VRAM budget overrides per service
- Async file writing with automatic directory creation

Usage:
    from backend.services.gpu_config_service import (
        GpuConfigService,
        GpuAssignment,
    )

    service = GpuConfigService(config_dir=Path("config"))
    assignments = [
        GpuAssignment(service_name="ai-llm", gpu_index=0),
        GpuAssignment(service_name="ai-enrichment", gpu_index=1, vram_budget_override=3.5),
    ]
    override_path, assignments_path = await service.write_config_files(
        assignments=assignments,
        strategy="vram_based",
    )
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path

import yaml

from backend.core.logging import get_logger

logger = get_logger(__name__)


@dataclass
class GpuAssignment:
    """Represents a GPU assignment for a service.

    Attributes:
        service_name: The name of the service (e.g., 'ai-llm', 'ai-detector').
        gpu_index: The GPU index to assign (0-based).
        vram_budget_override: Optional VRAM budget override in GB. When set,
            an environment variable VRAM_BUDGET_GB will be added to the service.
    """

    service_name: str
    gpu_index: int
    vram_budget_override: float | None = None


class GpuConfigService:
    """Service for generating GPU configuration files.

    This service generates docker-compose override files that specify GPU
    device assignments for containerized AI services. It supports:

    - GPU device pinning via NVIDIA container runtime
    - VRAM budget overrides via environment variables
    - Human-readable assignment files for inspection

    The generated files should be used with docker-compose/podman-compose:
        podman-compose -f docker-compose.prod.yml \\
                       -f config/docker-compose.gpu-override.yml up -d

    Attributes:
        config_dir: Directory where config files will be written.
        override_file: Path to the docker-compose.gpu-override.yml file.
        assignments_file: Path to the gpu-assignments.yml file.
    """

    def __init__(self, config_dir: Path | None = None) -> None:
        """Initialize the GPU config service.

        Args:
            config_dir: Directory for config files. Defaults to 'config'.
        """
        self.config_dir = config_dir if config_dir is not None else Path("config")
        self.override_file = self.config_dir / "docker-compose.gpu-override.yml"
        self.assignments_file = self.config_dir / "gpu-assignments.yml"
        logger.debug(f"GpuConfigService initialized with config_dir={self.config_dir}")

    def generate_override_content(self, assignments: list[GpuAssignment]) -> str:
        """Generate docker-compose.gpu-override.yml content.

        Creates a docker-compose override file that pins services to specific
        GPUs using the NVIDIA container runtime. Optionally includes VRAM
        budget environment variables.

        Args:
            assignments: List of GPU assignments for services.

        Returns:
            YAML content string with header comment and services configuration.

        Example output:
            # Auto-generated by GPU Config Service - DO NOT EDIT MANUALLY
            services:
              ai-llm:
                deploy:
                  resources:
                    reservations:
                      devices:
                        - driver: nvidia
                          device_ids:
                            - '0'
                          capabilities:
                            - gpu
        """
        services: dict[str, dict] = {}

        for assignment in assignments:
            service_config: dict = {
                "deploy": {
                    "resources": {
                        "reservations": {
                            "devices": [
                                {
                                    "driver": "nvidia",
                                    "device_ids": [str(assignment.gpu_index)],
                                    "capabilities": ["gpu"],
                                }
                            ]
                        }
                    }
                }
            }

            if assignment.vram_budget_override is not None:
                service_config["environment"] = [
                    f"VRAM_BUDGET_GB={assignment.vram_budget_override}"
                ]

            services[assignment.service_name] = service_config

        content: dict = {"services": services}

        header = "# Auto-generated by GPU Config Service - DO NOT EDIT MANUALLY\n"
        yaml_content: str = yaml.dump(content, default_flow_style=False, sort_keys=False)
        return header + yaml_content

    def generate_assignments_content(
        self,
        assignments: list[GpuAssignment],
        strategy: str,
    ) -> str:
        """Generate human-readable gpu-assignments.yml.

        Creates a YAML file documenting the current GPU assignments, strategy
        used, and timestamp for reference and debugging purposes.

        Args:
            assignments: List of GPU assignments for services.
            strategy: The assignment strategy used (e.g., 'manual', 'vram_based').

        Returns:
            YAML content string with header comment and assignment details.

        Example output:
            # Auto-generated - for reference only
            generated_at: '2025-01-23T10:30:00+00:00'
            strategy: vram_based
            assignments:
              ai-llm:
                gpu: 0
                vram_budget: null
              ai-enrichment:
                gpu: 1
                vram_budget: 3.5
        """
        data: dict = {
            "generated_at": datetime.now(UTC).isoformat(),
            "strategy": strategy,
            "assignments": {
                a.service_name: {
                    "gpu": a.gpu_index,
                    "vram_budget": a.vram_budget_override,
                }
                for a in assignments
            },
        }

        header = "# Auto-generated - for reference only\n"
        yaml_content: str = yaml.dump(data, default_flow_style=False, sort_keys=False)
        return header + yaml_content

    async def write_config_files(
        self,
        assignments: list[GpuAssignment],
        strategy: str,
    ) -> tuple[Path, Path]:
        """Write both config files to disk.

        Creates the config directory if it doesn't exist, then writes:
        1. docker-compose.gpu-override.yml - For docker-compose/podman-compose
        2. gpu-assignments.yml - Human-readable reference file

        Args:
            assignments: List of GPU assignments for services.
            strategy: The assignment strategy used.

        Returns:
            Tuple of (override_file_path, assignments_file_path).

        Raises:
            OSError: If directory creation or file writing fails.
        """
        logger.info(
            f"Writing GPU config files: strategy={strategy}, assignments={len(assignments)}"
        )

        # Create config directory if missing
        self.config_dir.mkdir(parents=True, exist_ok=True)

        # Write override file
        override_content = self.generate_override_content(assignments)
        self.override_file.write_text(override_content)
        logger.debug(f"Wrote override file: {self.override_file}")

        # Write assignments file
        assignments_content = self.generate_assignments_content(assignments, strategy)
        self.assignments_file.write_text(assignments_content)
        logger.debug(f"Wrote assignments file: {self.assignments_file}")

        logger.info(
            f"GPU config files written successfully: {self.override_file}, {self.assignments_file}"
        )

        return self.override_file, self.assignments_file
