"""`vlm_assess` contract models - the VLM path's single source of truth (spec §3).

`VlmVerdict` is what the constrained-decoding call must return: the schema the
client sends, the golden payload, and the shape snapshot all derive from this
module (drift doctrine - the E5 nvext defect is what happens when the sent
constraint and the expected shape are maintained separately). The JSON Schema
is `model_json_schema()`, generated by `scripts/gen-ai-contract.py` under
`VLM_OPS`; nothing here is hand-transcribed into the contract, and the contract
must never be hand-edited back.

`risk_level` is NOT a field: the model never emits a level (spec §3, Derived
row) - `SeverityService` derives it from `risk_score`.

Import discipline: `scripts/gen-ai-contract.py` imports this module by name at
generation time, so its import closure stays pydantic-only - no settings, no
DB, no `backend.api.schemas` (whose __init__ is a 700-line eager aggregate).
For that reason `VlmAssessContext` repeats the frozen AssessInput's fields
instead of importing that class; a test pins the two field sets together.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

Verdict = Literal["confirmed", "rejected", "uncertain"]


class VlmCriterion(BaseModel):
    """One §3 verification criterion. Field-compatible with the shipped
    `backend/api.schemas.event_verification.VerificationCriterion` (P0.4) - the
    API-side model is the wire mirror of this shape; the pin in
    scripts/test_gen_ai_contract.py keeps them from forking."""

    model_config = ConfigDict(extra="forbid")

    name: str = Field(min_length=1)
    passed: bool
    evidence: str = Field(min_length=1)


class VlmProvenance(BaseModel):
    """Who actually answered. `engine` is the serving engine's own reported
    id (llama.cpp build string, vLLM engine name) - OPENAI_VLM is
    engine-agnostic, so provenance, not the ProviderId, records the engine
    (spec §3, Slots)."""

    model_config = ConfigDict(extra="forbid")

    engine: str = Field(min_length=1)
    model_id: str = Field(min_length=1)


class VlmVerdict(BaseModel):
    """The constrained response for `vlm_assess` (spec §3).

    Deliberately NO extra keys (the wire carries no level; the batch id and
    other pipeline bookkeeping belong to the analyzer, not the model) and NO
    defaults on any field - under constrained decoding every field is
    required and emitted, and a default here would let a partially-echoed
    response pass validation while lying about a value."""

    model_config = ConfigDict(extra="forbid")

    verdict: Verdict
    risk_score: int = Field(ge=0, le=100)
    summary: str = Field(min_length=1)
    reasoning: str = Field(min_length=1)
    description: str = Field(min_length=1)
    criteria: list[VlmCriterion] = Field(min_length=1)
    provenance: VlmProvenance


class VlmAssessContext(BaseModel):
    """Wire mirror of the frozen `backend.evaluation.assess_input.AssessInput`
    (camera, detections, zones, zone_crossing, household, timestamp,
    specialist_outputs) - same field pattern as
    VlmCriterion/VerificationCriterion: mirror here, pin the field-set
    compatibility in scripts/test_gen_ai_contract.py, and the analyzer (1.3)
    converts store/DB snapshots into it, ONE code path for production and
    replay (spec §2). Mirrored rather than imported so this module's import
    closure stays pydantic-only for the generator. The corpus freeze is
    unaffected: the store's class and 421 frozen items are untouched (rev 6
    reopened AssessInput for the one optional `specialist_outputs` field,
    F11 ruling 4 — the mirror gains it by hand, and the field-set pins catch
    any future fork)."""

    model_config = ConfigDict(extra="forbid")

    camera_id: str
    detections: list[dict] = Field(default_factory=list)
    zones: list[str] = Field(default_factory=list)
    zone_crossing: bool = False
    household: dict = Field(default_factory=dict)
    timestamp: str
    specialist_outputs: dict[str, str] = Field(default_factory=dict)


class VlmAssessRequest(BaseModel):
    """The `vlm_assess` request side (spec §3): 1-4 image references plus the
    structured text context.

    `image_paths` (1-4, paths under the FTP root; each provider chooses a data
    URI or file://, and D10 keeps bytes out of this object) and `context` (the
    AssessInput mirror above). The specialist texts (faces/plates/re-ID) ride
    INSIDE the context - the snapshot is their one carrier, so production and
    replay read them from the same place (rev 6, F11 ruling 4; the VLM never
    originates them, spec §6)."""

    model_config = ConfigDict(extra="forbid")

    image_paths: list[str] = Field(min_length=1, max_length=4)
    context: VlmAssessContext
