"""Core infrastructure components."""

from backend.core.config import Settings, get_settings
from backend.core.database import (
    Base,
    close_db,
    get_db,
    get_engine,
    get_session,
    get_session_factory,
    init_db,
)
from backend.core.logging import (
    get_logger,
    get_request_id,
    sanitize_error,
    set_request_id,
    setup_logging,
)
from backend.core.metrics import (
    get_metrics_response,
    observe_ai_request_duration,
    observe_stage_duration,
    record_detection_processed,
    record_event_created,
    record_pipeline_error,
    set_queue_depth,
)
from backend.core.redis import (
    BackpressureStrategy,
    QueueAddResult,
    RedisClient,
    close_redis,
    get_redis,
    init_redis,
)
from backend.core.tls import (
    CertificateNotFoundError,
    CertificateValidationError,
    TLSConfigurationError,
    TLSError,
    create_ssl_context,
    generate_self_signed_cert,
    get_cert_info,
    get_tls_config,
    is_tls_enabled,
    load_certificate_paths,
    validate_certificate,
)

__all__ = [
    "BackpressureStrategy",
    "Base",
    "CertificateNotFoundError",
    "CertificateValidationError",
    "QueueAddResult",
    "RedisClient",
    "Settings",
    "TLSConfigurationError",
    "TLSError",
    "close_db",
    "close_redis",
    "create_ssl_context",
    "generate_self_signed_cert",
    "get_cert_info",
    "get_db",
    "get_engine",
    "get_logger",
    "get_metrics_response",
    "get_redis",
    "get_request_id",
    "get_session",
    "get_session_factory",
    "get_settings",
    "get_tls_config",
    "init_db",
    "init_redis",
    "is_tls_enabled",
    "load_certificate_paths",
    "observe_ai_request_duration",
    "observe_stage_duration",
    "record_detection_processed",
    "record_event_created",
    "record_pipeline_error",
    "sanitize_error",
    "set_queue_depth",
    "set_request_id",
    "setup_logging",
    "validate_certificate",
]
