"""Core infrastructure components."""

from backend.core.config import Settings, get_settings
from backend.core.database import (
    Base,
    close_db,
    get_db,
    get_engine,
    get_session,
    get_session_factory,
    init_db,
)
from backend.core.logging import (
    get_logger,
    get_request_id,
    sanitize_error,
    set_request_id,
    setup_logging,
)
from backend.core.metrics import (
    get_metrics_response,
    observe_ai_request_duration,
    observe_stage_duration,
    record_detection_processed,
    record_event_created,
    record_pipeline_error,
    set_queue_depth,
)
from backend.core.mime_types import (
    DEFAULT_IMAGE_MIME,
    DEFAULT_VIDEO_MIME,
    EXTENSION_TO_MIME,
    get_mime_type,
    get_mime_type_with_default,
    is_image_mime_type,
    is_supported_mime_type,
    is_video_mime_type,
    normalize_file_type,
)
from backend.core.redis import (
    RedisClient,
    close_redis,
    get_redis,
    get_redis_optional,
    init_redis,
)
from backend.core.tls import (
    TLSConfig,
    TLSMode,
    create_ssl_context,
    generate_self_signed_certificate,
    get_tls_config,
    validate_certificate_files,
)

__all__ = [
    "DEFAULT_IMAGE_MIME",
    "DEFAULT_VIDEO_MIME",
    "EXTENSION_TO_MIME",
    "Base",
    "RedisClient",
    "Settings",
    "TLSConfig",
    "TLSMode",
    "close_db",
    "close_redis",
    "create_ssl_context",
    "generate_self_signed_certificate",
    "get_db",
    "get_engine",
    "get_logger",
    "get_metrics_response",
    "get_mime_type",
    "get_mime_type_with_default",
    "get_redis",
    "get_redis_optional",
    "get_request_id",
    "get_session",
    "get_session_factory",
    "get_settings",
    "get_tls_config",
    "init_db",
    "init_redis",
    "is_image_mime_type",
    "is_supported_mime_type",
    "is_video_mime_type",
    "normalize_file_type",
    "observe_ai_request_duration",
    "observe_stage_duration",
    "record_detection_processed",
    "record_event_created",
    "record_pipeline_error",
    "sanitize_error",
    "set_queue_depth",
    "set_request_id",
    "setup_logging",
    "validate_certificate_files",
]
