#!/usr/bin/env python3
"""Interactive setup script for Home Security Intelligence.

Generates .env and docker-compose.override.yml files for user environment.
Supports two modes:
- Quick mode (default): Accept defaults with Enter
- Guided mode (--guided): Step-by-step with explanations
"""

import argparse
import platform
import secrets
import shutil
import socket
import subprocess
import sys
from datetime import datetime
from pathlib import Path
from typing import Any, TypedDict


class ServiceInfo(TypedDict):
    """Type definition for service configuration."""

    port: int
    category: str
    desc: str


# Service definitions with default ports
SERVICES: dict[str, ServiceInfo] = {
    "backend": {"port": 8000, "category": "Core", "desc": "Backend API"},
    "frontend": {"port": 5173, "category": "Core", "desc": "Frontend web UI"},
    "postgres": {"port": 5432, "category": "Core", "desc": "PostgreSQL database"},
    "redis": {"port": 6379, "category": "Core", "desc": "Redis cache/queue"},
    "rtdetr": {"port": 8090, "category": "AI", "desc": "RT-DETRv2 object detection"},
    "nemotron": {"port": 8091, "category": "AI", "desc": "Nemotron LLM reasoning"},
    "florence": {"port": 8092, "category": "AI", "desc": "Florence-2 vision-language"},
    "clip": {"port": 8093, "category": "AI", "desc": "CLIP embeddings"},
    "enrichment": {"port": 8094, "category": "AI", "desc": "Entity enrichment"},
    "grafana": {"port": 3002, "category": "Monitoring", "desc": "Grafana dashboards"},
    "prometheus": {"port": 9090, "category": "Monitoring", "desc": "Prometheus metrics"},
    "alertmanager": {"port": 3000, "category": "Monitoring", "desc": "Alert manager"},
    "redis_exporter": {"port": 9121, "category": "Monitoring", "desc": "Redis exporter"},
    "json_exporter": {"port": 7979, "category": "Monitoring", "desc": "JSON exporter"},
}


def check_port_available(port: int) -> bool:
    """Check if a port is available for binding.

    Args:
        port: Port number to check

    Returns:
        True if port is available, False if in use
    """
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        return s.connect_ex(("localhost", port)) != 0


def find_available_port(start: int) -> int:
    """Find the next available port starting from a given port.

    Args:
        start: Starting port number

    Returns:
        First available port >= start
    """
    port = start
    while not check_port_available(port):
        port += 1
        if port > 65535:
            raise RuntimeError(f"No available ports found starting from {start}")
    return port


def prompt_with_default(prompt: str, default: str) -> str:
    """Prompt user for input with a default value.

    Args:
        prompt: Prompt text to display
        default: Default value if user presses Enter

    Returns:
        User input or default value
    """
    try:
        user_input = input(f"{prompt} [{default}]: ").strip()
        return user_input if user_input else default
    except (EOFError, KeyboardInterrupt):
        print()
        return default


def generate_password(length: int = 16) -> str:
    """Generate a secure random password.

    Args:
        length: Desired password length

    Returns:
        URL-safe random string of specified length
    """
    return secrets.token_urlsafe(length)[:length]


def generate_env_content(config: dict) -> str:
    """Generate .env file content from configuration.

    Args:
        config: Dictionary containing camera_path, ai_models_path,
                postgres_password, ftp_password, and ports dict

    Returns:
        String content for .env file
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    ports = config.get("ports", {})

    lines = [
        f"# Generated by setup.py on {timestamp}",
        "# " + "=" * 59,
        "",
        "# -- Paths " + "-" * 50,
        f"CAMERA_PATH={config.get('camera_path', '/export/foscam')}",
        f"AI_MODELS_PATH={config.get('ai_models_path', '/export/ai_models')}",
        "",
        "# -- Credentials " + "-" * 44,
        f"POSTGRES_PASSWORD={config.get('postgres_password', '')}",
        f"FTP_PASSWORD={config.get('ftp_password', '')}",
        "",
        "# -- Database " + "-" * 47,
        "POSTGRES_USER=security",
        "POSTGRES_DB=security",
        f"DATABASE_URL=postgresql+asyncpg://security:{config.get('postgres_password', '')}@postgres:{ports.get('postgres', 5432)}/security",
        "",
        "# -- Service URLs " + "-" * 43,
        f"RTDETR_URL=http://ai-detector:{ports.get('rtdetr', 8090)}",
        f"NEMOTRON_URL=http://ai-llm:{ports.get('nemotron', 8091)}",
        f"FLORENCE_URL=http://ai-florence:{ports.get('florence', 8092)}",
        f"CLIP_URL=http://ai-clip:{ports.get('clip', 8093)}",
        f"ENRICHMENT_URL=http://ai-enrichment:{ports.get('enrichment', 8094)}",
        f"REDIS_URL=redis://redis:{ports.get('redis', 6379)}",
        "",
        "# -- Frontend Runtime Config " + "-" * 32,
        f"GRAFANA_URL=http://localhost:{ports.get('grafana', 3002)}",
        "",
    ]
    return "\n".join(lines)


def generate_docker_override_content(config: dict) -> str:
    """Generate docker-compose.override.yml content.

    Args:
        config: Dictionary containing camera_path, ai_models_path, and ports dict

    Returns:
        String content for docker-compose.override.yml file
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    ports = config.get("ports", {})
    camera_path = config.get("camera_path", "/export/foscam")

    lines = [
        f"# Generated by setup.py on {timestamp}",
        "# This file is auto-merged with docker-compose.prod.yml",
        "",
        "services:",
    ]

    service_configs = {
        "postgres": {"port": ports.get("postgres", 5432), "internal": 5432},
        "redis": {"port": ports.get("redis", 6379), "internal": 6379},
        "backend": {
            "port": ports.get("backend", 8000),
            "internal": 8000,
            "volumes": [f"{camera_path}:/cameras:ro"],
        },
        "ai-detector": {"port": ports.get("rtdetr", 8090), "internal": 8090},
        "ai-llm": {"port": ports.get("nemotron", 8091), "internal": 8091},
        "ai-florence": {"port": ports.get("florence", 8092), "internal": 8092},
        "ai-clip": {"port": ports.get("clip", 8093), "internal": 8093},
        "ai-enrichment": {"port": ports.get("enrichment", 8094), "internal": 8094},
        "frontend": {"port": ports.get("frontend", 5173), "internal": 80},
        "grafana": {"port": ports.get("grafana", 3002), "internal": 3000},
        "prometheus": {"port": ports.get("prometheus", 9090), "internal": 9090},
        "alertmanager": {"port": ports.get("alertmanager", 3000), "internal": 9093},
        "redis-exporter": {"port": ports.get("redis_exporter", 9121), "internal": 9121},
        "json-exporter": {"port": ports.get("json_exporter", 7979), "internal": 7979},
    }

    for service, cfg in service_configs.items():
        lines.append(f"  {service}:")
        lines.append("    ports:")
        lines.append(f'      - "{cfg["port"]}:{cfg["internal"]}"')
        if "volumes" in cfg:
            lines.append("    volumes:")
            for vol in cfg["volumes"]:
                lines.append(f"      - {vol}")
        lines.append("")

    return "\n".join(lines)


def run_quick_mode() -> dict:
    """Run quick setup mode with minimal prompts.

    Returns:
        Configuration dictionary
    """
    print("=" * 60)
    print("  Home Security Intelligence - Quick Setup")
    print("=" * 60)
    print()

    # Check port conflicts
    print("Checking for port conflicts...")
    conflicts = []
    ports = {}
    for service, info in SERVICES.items():
        default_port = info["port"]
        if check_port_available(default_port):
            ports[service] = default_port
        else:
            available = find_available_port(default_port)
            ports[service] = available
            conflicts.append(f"  {service}: {default_port} -> {available}")

    if conflicts:
        print("! Port conflicts detected, using alternatives:")
        for c in conflicts:
            print(c)
    else:
        print("* All default ports available")
    print()

    # Paths
    print("-- Paths " + "-" * 52)
    camera_path = prompt_with_default("Camera upload path", "/export/foscam")
    ai_models_path = prompt_with_default("AI models path", "/export/ai_models")
    print()

    # Credentials
    print("-- Credentials " + "-" * 46)
    postgres_password = prompt_with_default("Database password", generate_password())
    ftp_password = prompt_with_default("FTP password", generate_password())
    print()

    # Ports (optional customization)
    print("-- Ports (press Enter to keep defaults) " + "-" * 21)
    for service, info in SERVICES.items():
        suggested = ports[service]
        custom = prompt_with_default(f"{info['desc']}", str(suggested))
        try:
            ports[service] = int(custom)
        except ValueError:
            ports[service] = suggested
    print()

    return {
        "camera_path": camera_path,
        "ai_models_path": ai_models_path,
        "postgres_password": postgres_password,
        "ftp_password": ftp_password,
        "ports": ports,
    }


def write_config_files(config: dict[str, Any], output_dir: str = ".") -> tuple[Path, Path]:
    """Write configuration files to disk.

    Args:
        config: Configuration dictionary
        output_dir: Directory to write files to

    Returns:
        Tuple of (env_path, override_path)
    """
    output = Path(output_dir)
    output.mkdir(parents=True, exist_ok=True)

    env_path = output / ".env"
    override_path = output / "docker-compose.override.yml"

    env_content = generate_env_content(config)
    override_content = generate_docker_override_content(config)

    env_path.write_text(env_content)
    override_path.write_text(override_content)

    return env_path, override_path


def configure_firewall(ports: list[int]) -> bool:
    """Configure Linux firewall to allow specified ports.

    Args:
        ports: List of port numbers to open

    Returns:
        True if successful, False otherwise
    """
    if platform.system() != "Linux":
        return False

    # Try firewall-cmd (Fedora/RHEL/CentOS)
    if shutil.which("firewall-cmd"):
        try:
            for port in ports:
                subprocess.run(  # noqa: S603 - firewall config requires subprocess
                    ["firewall-cmd", "--permanent", f"--add-port={port}/tcp"],  # noqa: S607
                    check=True,
                    capture_output=True,
                )
            subprocess.run(
                ["firewall-cmd", "--reload"],  # noqa: S607
                check=True,
                capture_output=True,
            )
            return True
        except subprocess.CalledProcessError:
            return False

    # Try ufw (Ubuntu/Debian)
    if shutil.which("ufw"):
        try:
            for port in ports:
                subprocess.run(  # noqa: S603 - firewall config requires subprocess
                    ["ufw", "allow", f"{port}/tcp"],  # noqa: S607
                    check=True,
                    capture_output=True,
                )
            return True
        except subprocess.CalledProcessError:
            return False

    return False


def main() -> None:
    """Main entry point for setup script."""
    parser = argparse.ArgumentParser(description="Interactive setup for Home Security Intelligence")
    parser.add_argument(
        "--guided",
        action="store_true",
        help="Run in guided mode with detailed explanations",
    )
    parser.add_argument(
        "--output-dir",
        default=".",
        help="Output directory for generated files (default: current directory)",
    )
    args = parser.parse_args()

    try:
        if args.guided:
            print("Guided mode not yet implemented")
            config = run_quick_mode()  # Fallback to quick mode
        else:
            config = run_quick_mode()

        # Write configuration files
        env_path, override_path = write_config_files(config, args.output_dir)

        print("=" * 60)
        print("Generated:")
        print(f"  - {env_path}")
        print(f"  - {override_path}")
        print()

        # Offer firewall configuration on Linux
        if platform.system() == "Linux":
            frontend_port = config["ports"].get("frontend", 5173)
            grafana_port = config["ports"].get("grafana", 3002)

            answer = prompt_with_default(
                f"Open firewall ports for frontend ({frontend_port}) and Grafana ({grafana_port})?",
                "n",
            )
            if answer.lower() in ("y", "yes"):
                if configure_firewall([frontend_port, grafana_port]):
                    print("Firewall configured")
                else:
                    print("Could not configure firewall (may need sudo)")

        print()
        print("Ready! Run: docker-compose -f docker-compose.prod.yml up -d")
        print("=" * 60)

    except KeyboardInterrupt:
        print("\n\nSetup cancelled.")
        sys.exit(1)


if __name__ == "__main__":
    main()
