"""Seeded response generators for the FakeProvider (WP8.2).

THE determinism contract: responses are generated from a hash of the
operation id (plus payload-derived echo fields), never from wall-clock or
process state, and serialized through ONE json.dumps(sort_keys=True,
separators=...) call. Two identical requests are byte-identical - the
plan's literal Done-when.

SCHEMA-DRIVEN means literal: every operation that has a committed WP7.2
response snapshot has its response GENERATED BY WALKING THAT SNAPSHOT
(backend/ai_contract/schemas/<op>.response.json), with named semantic
overrides where the plan pins a shipped-correct shape the schema alone
cannot express (768-dim L2 embedding, bbox dict-vs-list, OCR 8-coord
quads, class vocabularies). The fake therefore cannot drift from the
contract: the snapshot IS the generator input, and the contract suite
re-validates the output against the same snapshot.

The seven ops without a committed snapshot have the gap documented at the
bottom of this file (GEN_GAPS): four live only on the heavy enrichment
server's pydantic models (SystemStatus etc. - mirrored field-for-field
here, pinned by test_fake_provider's AST mirror test) and three return a
BARE dict on the deployed gateway (WP7.4's pinned shape).

No ai.* imports (package rule, see ../__init__.py): the class vocabularies
are carried as data and pinned against their sources by AST mirror tests.
"""

from __future__ import annotations

import hashlib
import json
import math
import random
from functools import lru_cache
from pathlib import Path
from typing import Any

SCHEMA_DIR = Path(__file__).resolve().parents[1] / "schemas"

# ai/yolo26/model.py:151 SECURITY_CLASSES (and ai/triton/client.py:230):
# what the per-model native server filters to. Mirrored as DATA; the mirror
# test AST-pins equality with the source (a rename upstream reddens there).
SECURITY_CLASSES: frozenset[str] = frozenset(
    {"person", "car", "truck", "dog", "cat", "bird", "bicycle", "motorcycle", "bus"}
)

# ai/gateway/adapters/yolo26.py:42 COCO_CLASSES, gateway order - the
# UNFILTERED profile. The deployed provider is this one (WP7.3 Tier A:
# adapters/yolo26.py does not filter), so "gateway" is the fake's DEFAULT.
GATEWAY_CLASSES: tuple[str, ...] = (
    "person",
    "bicycle",
    "car",
    "motorcycle",
    "airplane",
    "bus",
    "train",
    "truck",
    "boat",
    "traffic light",
    "fire hydrant",
    "stop sign",
    "parking meter",
    "bench",
    "bird",
    "cat",
    "dog",
    "horse",
    "sheep",
    "cow",
    "elephant",
    "bear",
    "zebra",
    "giraffe",
    "backpack",
    "umbrella",
    "handbag",
    "tie",
    "suitcase",
    "frisbee",
    "skis",
    "snowboard",
    "sports ball",
    "kite",
    "baseball bat",
    "baseball glove",
    "skateboard",
    "surfboard",
    "tennis racket",
    "bottle",
    "wine glass",
    "cup",
    "fork",
    "knife",
    "spoon",
    "bowl",
    "banana",
    "apple",
    "sandwich",
    "orange",
    "broccoli",
    "carrot",
    "hot dog",
    "pizza",
    "donut",
    "cake",
    "chair",
    "couch",
    "potted plant",
    "bed",
    "dining table",
    "toilet",
    "tv",
    "laptop",
    "mouse",
    "remote",
    "keyboard",
    "cell phone",
    "microwave",
    "oven",
    "toaster",
    "sink",
    "refrigerator",
    "book",
    "clock",
    "vase",
    "scissors",
    "teddy bear",
    "hair drier",
    "toothbrush",
)

# The shipped-correct fixed timing values (WP7.4: inference_time_ms, NEVER
# processing_time_ms; seeded, never wall-clock - byte identity depends on it).
_FAKE_INFERENCE_MS = 12.5
_FAKE_TOTAL_MS = 25.0
_FAKE_FRAME = (640, 480)


def _rng_for(*parts: object) -> random.Random:
    """Fresh seeded PRNG per call-site path: state never bleeds between
    ops, requests, or tests (pytest-randomly safe), and the seed derives
    only from the parts, not from a counter."""
    digest = hashlib.sha256("|".join(str(p) for p in parts).encode("utf-8")).hexdigest()
    return random.Random(int(digest[:16], 16))  # noqa: S311 - seeded fixture, not security


@lru_cache(maxsize=1)
def _snapshots() -> dict[str, dict[str, Any]]:
    out: dict[str, dict[str, Any]] = {}
    for path in SCHEMA_DIR.glob("*.response.json"):
        op_id = path.name[: -len(".response.json")]
        out[op_id] = json.loads(path.read_text(encoding="utf-8"))
    return out


def snapshot_for(op_id: str) -> dict[str, Any] | None:
    return _snapshots().get(op_id)


def classes_for_profile(profile: str) -> tuple[str, ...]:
    if profile == "security":
        return tuple(sorted(SECURITY_CLASSES))
    return GATEWAY_CLASSES


# --- semantic overrides ---------------------------------------------------
# The plan's shipped-correct bullets: shapes the JSON Schema (type-only)
# cannot express. _OVERRIDES maps (op_id, property) -> (kind, arg); the
# walker consults it BEFORE generic generation.


def _unit_embedding(dim: int, *parts: object) -> list[float]:
    rng = _rng_for("embedding", dim, *parts)
    raw = [rng.uniform(-1.0, 1.0) for _ in range(dim)]
    norm = math.sqrt(sum(v * v for v in raw))
    return [v / norm for v in raw]


def _florence_bbox(arity: int, *parts: object) -> list[float]:
    """list-of-FLOATS [x1,y1,x2,y2]; OCR regions carry EIGHT floats (quad
    corners flattened, ai/florence/model.py:190,1101). Arity is the bug the
    plan calls out - a fake emitting 4 there trains consumers wrong."""
    rng = _rng_for("bbox", arity, *parts)
    x1, y1 = rng.uniform(8.0, 128.0), rng.uniform(8.0, 96.0)
    x2, y2 = x1 + rng.uniform(16.0, 240.0), y1 + rng.uniform(16.0, 180.0)
    coords = [round(x1, 4), round(y1, 4), round(x2, 4), round(y2, 4)]
    if arity == 8:  # quad corners: (x1,y1) (x2,y1) (x2,y2) (x1,y2)
        return [
            coords[0],
            coords[1],
            coords[2],
            coords[1],
            coords[2],
            coords[3],
            coords[0],
            coords[3],
        ]
    if arity != 4:
        raise ValueError(f"unexpected florence bbox arity {arity}")
    return coords


def _class_name(profile: str, i: int, op_id: str) -> str:
    table = classes_for_profile(profile)
    rng = _rng_for("class", profile, i, op_id)
    return table[rng.randrange(len(table))]


def _confidence(i: int, op_id: str) -> float:
    rng = _rng_for("conf", i, op_id)
    return round(rng.uniform(0.55, 0.97), 4)


def _yolo_bbox_dict(i: int, op_id: str) -> dict[str, int]:
    """DICT of INTS, absolute pixels, in-frame (WP7.4 deployed shape:
    {x,y,width,height}; clamping is the gateway's job, the fake just stays
    inside the frame so it is always clamp-valid)."""
    rng = _rng_for("yolobbox", i, op_id)
    w, h = _FAKE_FRAME
    bw = rng.randint(24, 180)
    bh = rng.randint(24, 150)
    return {
        "x": rng.randint(0, w - bw),
        "y": rng.randint(0, h - bh),
        "width": bw,
        "height": bh,
    }


# (op_id, property-name) -> (kind, arg). Overrides consulted BEFORE generic
# generation; this is where the plan's shipped-correct bullets live:
#   * embedding: 768-dim CLIP (512 reid) L2-normalized;
#   * bbox: dict-of-ints on the yolo ops, list-of-floats elsewhere, 8-coord
#     quads on the OCR-region path (ai/florence/model.py:190,1101);
#   * inference_time_ms constants (never wall-clock; never processing_time_ms).
# "class" (the detection key, a pydantic alias over class_name) and the
# per-profile class vocabulary belong to the yolo LITERAL generators (no
# snapshots exist for those three ops); florence's label / enrichment's
# type-keyed maps are exercised through the generic walker.
_OVERRIDES: dict[tuple[str, str], tuple[str, Any]] = {}
_OVERRIDES[("clip_embed", "embedding")] = ("unit_embedding", 768)
_OVERRIDES[("enrich_lt_person_reid", "embedding")] = ("unit_embedding", 512)
_OVERRIDES[("enrich_lt_person_reid", "embedding_dimension")] = ("const", 512)
# florence ops: 4-coord float bboxes everywhere except the OCR-region quad
for _op in (
    "florence_batch_extract",
    "florence_dense_caption",
    "florence_describe_region",
    "florence_detect",
    "florence_detect_security_objects",
    "florence_phrase_grounding",
):
    _OVERRIDES[(_op, "bbox")] = ("florence_bbox", 4)
# GroundedPhrase.bboxes is list[list[float]] (model.py:407) - a LIST of
# quads-per-phrase, not one flat bbox. A bare "florence_bbox" here would
# emit floats where the schema demands arrays (jsonschema: "168.0 is not
# of type 'array'").
_OVERRIDES[("florence_phrase_grounding", "bboxes")] = ("florence_bbox_list", 2)
_OVERRIDES[("florence_ocr_with_regions", "bbox")] = ("florence_bbox", 8)
# Qualified keys ("<DefName>.<prop>", lookup falls back to the bare name,
# exact match wins) exist because florence_analyze_scene once carried BOTH
# caption regions (4-coord) and text_regions (8-coord quads) under one
# property name; A7.2 deleted that op, but the mechanism stays - the
# walker's def-qualification is exercised by the docstring example below.
# llm fixed bodies (shape comes from snapshots; values pinned here)
_OVERRIDES[("llm_completion", "content")] = ("const", "the quick brown fox")
_OVERRIDES[("llm_completion", "tokens_predicted")] = ("const", 9)
_OVERRIDES[("llm_chat_completion", "content")] = ("const", "a person walks a dog")
# llm_slots: the snapshot is array-of-free-form-object (llama.cpp /slots
# scrape, performance_collector.py:214 reads state + n_ctx) - the walker
# cannot invent faithful slot fields, so the value is pinned from the
# consumer's own expectations.
_OVERRIDES[("llm_slots", "llm_slots")] = (
    "const",
    [
        {"id": 0, "n_ctx": 4096, "n_ctx_seq": 512, "state": 1},
        {"id": 1, "n_ctx": 4096, "n_ctx_seq": 512, "state": 0},
    ],
)


# --- generic snapshot walker ----------------------------------------------


def _resolve(node: dict[str, Any], ctx: dict[str, Any]) -> tuple[dict[str, Any], str]:
    """Follow $ref chains; return (node, def_name). The def name qualifies
    property overrides so an op carrying TWO different bbox definitions
    (historically analyze_scene: CaptionedRegion 4-coord AND OCRRegion
    8-coord - A7.2 deleted that op; the qualification mechanism stays) can pin
    each - a bare-name match alone could not tell them apart."""
    def_name = ""
    while "$ref" in node:
        def_name = node["$ref"].rsplit("/", 1)[-1]
        node = ctx["defs"][def_name]
    return node, def_name


def _gen_value(  # noqa: PLR0911 - one return per JSON-Schema type is the shape of a type dispatcher
    node: dict[str, Any], name: str, ctx: dict[str, Any], i: int = 0, qual: str = ""
) -> Any:
    """Generate a schema-valid value for one property. Deterministic: every
    branch consumes only the (op_id, name, i) seed path carried in ctx."""
    op_id = ctx["op_id"]
    qualified = f"{qual}.{name}" if qual else name
    override = _OVERRIDES.get((op_id, qualified)) or _OVERRIDES.get((op_id, name))
    if override is not None:
        kind, arg = override
        if kind == "unit_embedding":
            return _unit_embedding(arg, op_id)
        if kind == "const":
            return arg
        if kind == "florence_bbox":
            return _florence_bbox(arg, op_id, qualified, i)
        if kind == "florence_bbox_list":
            # list[list[float]]: N bboxes (GroundedPhrase.bboxes - a phrase
            # may match several objects, model.py:402-407).
            return [_florence_bbox(4, op_id, qualified, j) for j in range(arg)]
        raise ValueError(f"{op_id}: unknown override kind {kind}")
    node, def_name = _resolve(node, ctx)
    qual = def_name or qual
    if "anyOf" in node:
        # Deterministic branch choice: NULLABLE schemas here are genuinely
        # optional metadata (ensemble_metadata) - pick the non-null branch,
        # never the null one, so the fake exercises the populated shape.
        branches = [b for b in node["anyOf"] if b.get("type") != "null"] or node["anyOf"]
        return _gen_value(branches[0], name, ctx, i, qual)
    if "enum" in node:
        return node["enum"][0]
    t = node.get("type")
    if t == "number":
        if name == "inference_time_ms":
            return _FAKE_INFERENCE_MS
        if name == "total_inference_time_ms":
            return _FAKE_TOTAL_MS
        return round(_rng_for(op_id, qualified, i, "num").uniform(0.1, 0.9), 4)
    if t == "integer":
        return _rng_for(op_id, qualified, i, "int").randint(1, 8)
    if t == "boolean":
        return _rng_for(op_id, qualified, i, "bool").random() < 0.5
    if t == "string":
        return f"{name}_{_rng_for(op_id, qualified, i, 'str').randint(100, 999)}"
    if t == "array":
        return _gen_array(node, name, ctx, qual)
    if t == "object":
        if "properties" in node:
            return {k: _gen_value(v, k, ctx, 0, qual) for k, v in node["properties"].items()}
        # free-form object (scores/similarities/enrichments maps)
        rng = _rng_for(op_id, qualified, "free-obj")
        return {
            "alpha": round(rng.uniform(0.1, 0.9), 4),
            "bravo": round(rng.uniform(0.1, 0.9), 4),
        }
    raise ValueError(f"{op_id}: cannot generate value for schema {node!r} (name {name})")


def _gen_array(node: dict[str, Any], name: str, ctx: dict[str, Any], qual: str = "") -> list[Any]:
    items = node.get("items", {})
    item_type, _ = _resolve(items, ctx)
    count = 2 if item_type.get("type") != "string" else 1
    # minItems (e.g. a 4-coord bbox array) outranks the default 2 - a
    # shorter instance violates the snapshot we validate against.
    count = max(count, node.get("minItems") or 1)
    return [_gen_value(items, f"{name}.{i}", ctx, i, qual) for i in range(count)]


def generate_from_snapshot(op_id: str, profile: str = "gateway") -> dict[str, Any] | list[Any]:
    schema = snapshot_for(op_id)
    if schema is None:
        raise KeyError(f"{op_id} has no committed response snapshot - use the literal generator")
    ctx = {"op_id": op_id, "defs": schema.get("$defs", {}), "profile": profile}
    result = _gen_value(schema, op_id, ctx)
    if not isinstance(result, dict | list):
        raise TypeError(f"{op_id}: snapshot produced {type(result)}")
    return result


def create_response_bytes(obj: Any) -> bytes:
    """The ONE serializer. sort_keys + compact separators = the byte-identity
    mechanism; dict insertion order cannot leak, whitespace cannot vary."""
    return json.dumps(obj, sort_keys=True, separators=(",", ":")).encode("utf-8")


# --- literal generators for the seven GEN_GAPS ops ------------------------
#
# GEN_GAPS (recorded in the WP8.2 ledger; each op DOES have a committed
# snapshot now - the generator extended to snapshot what WAS snapshotable -
# but the WALKER cannot produce faithful values for these seven, so they
# route here instead:
#   * yolo26_detect / yolo26_detect_batch / yolo26_segment: the routes
#     declare `-> dict[str, Any]` (no pydantic model); the committed
#     snapshot is the honest BARE dict (+ x-deployed-keys naming the WP7.4
#     shape). A walker over a bare dict emits {}-ish filler; the deployed
#     keys/values below are the pinned truth the whole suite consumes.
#   * model_status / model_preload / model_unload / object_distance: the
#     committed snapshots now come from the REAL server classes
#     (AST-extracted SystemStatus/ModelPreloadResponse/... by
#     gen-ai-contract, no import of the heavy module) - and the literals
#     below are validated against them, which proves the mirror. A generic
#     walker would emit "status_471" where the deployed truth is "loaded".
# Either way the response is still schema-VALIDATED against the committed
# snapshot - the schema-driven guarantee holds for all 37.

_YOLO_DETECT_KEYS = ("detections", "image_width", "image_height", "inference_time_ms")


def _yolo_detection(i: int, op_id: str, profile: str) -> dict[str, Any]:
    return {
        "class": _class_name(profile, i, op_id),
        "confidence": _confidence(i, op_id),
        "bbox": _yolo_bbox_dict(i, op_id),
    }


def _literal_generate(op_id: str, payload: Any, profile: str) -> dict[str, Any]:
    rng = _rng_for("literal", op_id)
    if op_id in ("yolo26_detect", "yolo26_segment"):
        w, h = _FAKE_FRAME
        return {
            "detections": [_yolo_detection(i, op_id, profile) for i in range(3)],
            "image_width": w,
            "image_height": h,
            "inference_time_ms": _FAKE_INFERENCE_MS,
        }
    if op_id == "yolo26_detect_batch":
        w, h = _FAKE_FRAME
        # Gateway batch item shape (adapters/yolo26.py:421-427): NO
        # per-item inference_time_ms; the total carries it.
        return {
            "results": [
                {
                    "detections": [_yolo_detection(i, op_id, profile)],
                    "image_width": w,
                    "image_height": h,
                }
                for i in range(2)
            ],
            "total_inference_time_ms": _FAKE_TOTAL_MS,
            "batch_size": 2,
        }
    if op_id == "model_status":
        # ai/enrichment/model.py:1666 SystemStatus (field-for-field).
        return {
            "status": "healthy",
            "vram_total_mb": 24576,
            "vram_used_mb": 8192,
            "vram_available_mb": 16384,
            "vram_budget_mb": 20480,
            "loaded_models": [
                {
                    "name": "enrichment_heavy",
                    "loaded": True,
                    "vram_mb": 4096,
                    "priority": "high",
                    "last_used": "2026-01-01T00:00:00+00:00",
                }
            ],
            "pending_loads": [],
            "uptime_seconds": 3600.0,
        }
    if op_id == "model_preload":
        # ai/enrichment/model.py:1687 ModelPreloadResponse.
        model = payload.get("model_name") if isinstance(payload, dict) else None
        return {
            "status": "loaded",
            "model": model if isinstance(model, str) else "enrichment_heavy",
            "message": "fake: preload accepted",
        }
    if op_id == "model_unload":
        # ai/enrichment/model.py:1695 ModelUnloadResponse.
        model = payload.get("model_name") if isinstance(payload, dict) else None
        return {
            "status": "unloaded",
            "model": model if isinstance(model, str) else "enrichment_heavy",
        }
    if op_id == "object_distance":
        # ai/enrichment/model.py:1627 ObjectDistanceResponse.
        return {
            "estimated_distance_m": round(rng.uniform(0.5, 8.0), 2),
            "relative_depth": round(rng.uniform(0.1, 0.9), 3),
            "proximity_label": "medium",
            "inference_time_ms": _FAKE_INFERENCE_MS,
        }
    raise KeyError(f"{op_id}: no snapshot and no literal generator")


_LITERAL_OPS = frozenset(
    {
        "yolo26_detect",
        "yolo26_detect_batch",
        "yolo26_segment",
        "model_status",
        "model_preload",
        "model_unload",
        "object_distance",
    }
)


def _softmax_over_labels(labels: list[str], op_id: str) -> tuple[dict[str, float], str]:
    """WP8.3 N2a: /classify is a SOFTMAX over exactly the REQUESTED labels —
    torch.softmax at ai/clip/model.py:919 and the gateway's manual
    exp(s - s.max())/(sum + 1e-8) with round(·, 6) at
    ai/gateway/adapters/clip.py:427-430. The committed snapshot's scores field
    is a free-form map (it cannot name labels it has none of), so the generic
    walker emits {alpha, bravo} ignoring the request — the divergence the
    conformance suite caught red. Echo-precedent: model_preload/unload already
    derive values from the payload (:463, :471). Seed derives from the labels
    (str-parts), so two identical requests stay BYTE-identical."""
    rng = _rng_for("softmax", op_id, "|".join(labels))
    logits = [rng.uniform(-2.0, 2.0) for _ in labels]
    exps = [math.exp(x - max(logits)) for x in logits]
    total = sum(exps) + 1e-8  # gateway epsilon guard, clip.py:428
    scores = {lab: round(e / total, 6) for lab, e in zip(labels, exps, strict=True)}
    top = max(range(len(exps)), key=exps.__getitem__)  # np.argmax first-wins parity
    return scores, labels[top]


def generate(op_id: str, payload: Any = None, profile: str = "gateway") -> Any:
    """The one entry point: the seven GEN_GAPS ops route to the literal
    deployed-shape generator; the other 31 are WALKED from their committed
    snapshot. Both paths are schema-VALIDATED post-generation (validate()
    below) so the schema-driven guarantee holds for all 37: a snapshot edit
    that makes the fake's output nonconformant reddens the suite either way."""
    value: Any
    if op_id in _LITERAL_OPS:
        value = _literal_generate(op_id, payload, profile)
    elif snapshot_for(op_id) is not None:
        value = generate_from_snapshot(op_id, profile)
    else:
        raise KeyError(f"{op_id}: no snapshot and not a literal op")
    if op_id == "clip_classify" and isinstance(payload, dict):
        labels = payload.get("labels")
        if isinstance(labels, list) and labels and all(isinstance(x, str) for x in labels):
            # payload None / labels absent keeps the walked shape (WP8.2
            # direct-generate tests drive it that way and stay green).
            scores, top_label = _softmax_over_labels(labels, op_id)
            value["scores"] = scores
            value["top_label"] = top_label
    validate(op_id, value)
    return value


def validate(op_id: str, value: Any) -> None:
    """Validate a generated response against the committed snapshot. The
    fake failing its OWN contract here is a loud bug, never a silent drift."""
    import jsonschema

    schema = snapshot_for(op_id)
    if schema is None:
        return
    jsonschema.validate(value, schema)
