"""Seeded response generators for the FakeProvider (WP8.2).

THE determinism contract: responses are generated from a hash of the
operation id (plus payload-derived echo fields), never from wall-clock or
process state, and serialized through ONE json.dumps(sort_keys=True,
separators=...) call. Two identical requests are byte-identical - the
plan's literal Done-when.

SCHEMA-DRIVEN means literal: every operation that has a committed WP7.2
response snapshot has its response GENERATED BY WALKING THAT SNAPSHOT
(backend/ai_contract/schemas/<op>.response.json), with named semantic
overrides where the plan pins a shipped-correct shape the schema alone
cannot express (the light lane's 512-dim L2-normalized reid embedding, the
class vocabularies). The fake therefore cannot drift from the contract: the
snapshot IS the generator input, and the contract suite re-validates the
output against the same snapshot.

The GEN_GAPS ops (yolo26_detect/_batch/segment) have a committed snapshot but
the walker cannot produce faithful values for them - their routes declare a
BARE dict - so they are generated literally from the deployed surface; the
gap is documented at the bottom of this file.

R8 S3 (2026-09-29, owner rulings 1 + 5) pruned the override and literal
entries whose op ids retired with the Florence provider and the CLIP/pruned-
model prune; those blocks' comments record what left and where the lesson
lives now.

No ai.* imports (package rule, see ../__init__.py): the class vocabularies
are carried as data and pinned against their sources by AST mirror tests.
"""

from __future__ import annotations

import hashlib
import json
import math
import random
from functools import lru_cache
from pathlib import Path
from typing import Any

SCHEMA_DIR = Path(__file__).resolve().parents[1] / "schemas"

# ai/yolo26/model.py:151 SECURITY_CLASSES (and ai/triton/client.py:230):
# what the per-model native server filters to. Mirrored as DATA; the mirror
# test AST-pins equality with the source (a rename upstream reddens there).
SECURITY_CLASSES: frozenset[str] = frozenset(
    {"person", "car", "truck", "dog", "cat", "bird", "bicycle", "motorcycle", "bus"}
)

# ai/gateway/adapters/yolo26.py:42 COCO_CLASSES, gateway order - the
# UNFILTERED profile. The deployed provider is this one (WP7.3 Tier A:
# adapters/yolo26.py does not filter), so "gateway" is the fake's DEFAULT.
GATEWAY_CLASSES: tuple[str, ...] = (
    "person",
    "bicycle",
    "car",
    "motorcycle",
    "airplane",
    "bus",
    "train",
    "truck",
    "boat",
    "traffic light",
    "fire hydrant",
    "stop sign",
    "parking meter",
    "bench",
    "bird",
    "cat",
    "dog",
    "horse",
    "sheep",
    "cow",
    "elephant",
    "bear",
    "zebra",
    "giraffe",
    "backpack",
    "umbrella",
    "handbag",
    "tie",
    "suitcase",
    "frisbee",
    "skis",
    "snowboard",
    "sports ball",
    "kite",
    "baseball bat",
    "baseball glove",
    "skateboard",
    "surfboard",
    "tennis racket",
    "bottle",
    "wine glass",
    "cup",
    "fork",
    "knife",
    "spoon",
    "bowl",
    "banana",
    "apple",
    "sandwich",
    "orange",
    "broccoli",
    "carrot",
    "hot dog",
    "pizza",
    "donut",
    "cake",
    "chair",
    "couch",
    "potted plant",
    "bed",
    "dining table",
    "toilet",
    "tv",
    "laptop",
    "mouse",
    "remote",
    "keyboard",
    "cell phone",
    "microwave",
    "oven",
    "toaster",
    "sink",
    "refrigerator",
    "book",
    "clock",
    "vase",
    "scissors",
    "teddy bear",
    "hair drier",
    "toothbrush",
)

# The shipped-correct fixed timing values (WP7.4: inference_time_ms, NEVER
# processing_time_ms; seeded, never wall-clock - byte identity depends on it).
_FAKE_INFERENCE_MS = 12.5
_FAKE_TOTAL_MS = 25.0
_FAKE_FRAME = (640, 480)


def _rng_for(*parts: object) -> random.Random:
    """Fresh seeded PRNG per call-site path: state never bleeds between
    ops, requests, or tests (pytest-randomly safe), and the seed derives
    only from the parts, not from a counter."""
    digest = hashlib.sha256("|".join(str(p) for p in parts).encode("utf-8")).hexdigest()
    return random.Random(int(digest[:16], 16))  # noqa: S311 - seeded fixture, not security


@lru_cache(maxsize=1)
def _snapshots() -> dict[str, dict[str, Any]]:
    out: dict[str, dict[str, Any]] = {}
    for path in SCHEMA_DIR.glob("*.response.json"):
        op_id = path.name[: -len(".response.json")]
        out[op_id] = json.loads(path.read_text(encoding="utf-8"))
    return out


def snapshot_for(op_id: str) -> dict[str, Any] | None:
    return _snapshots().get(op_id)


def classes_for_profile(profile: str) -> tuple[str, ...]:
    if profile == "security":
        return tuple(sorted(SECURITY_CLASSES))
    return GATEWAY_CLASSES


# --- semantic overrides ---------------------------------------------------
# The plan's shipped-correct bullets: shapes the JSON Schema (type-only)
# cannot express. _OVERRIDES maps (op_id, property) -> (kind, arg); the
# walker consults it BEFORE generic generation.


def _unit_embedding(dim: int, *parts: object) -> list[float]:
    rng = _rng_for("embedding", dim, *parts)
    raw = [rng.uniform(-1.0, 1.0) for _ in range(dim)]
    norm = math.sqrt(sum(v * v for v in raw))
    return [v / norm for v in raw]


def _class_name(profile: str, i: int, op_id: str) -> str:
    table = classes_for_profile(profile)
    rng = _rng_for("class", profile, i, op_id)
    return table[rng.randrange(len(table))]


def _confidence(i: int, op_id: str) -> float:
    rng = _rng_for("conf", i, op_id)
    return round(rng.uniform(0.55, 0.97), 4)


def _yolo_bbox_dict(i: int, op_id: str) -> dict[str, int]:
    """DICT of INTS, absolute pixels, in-frame (WP7.4 deployed shape:
    {x,y,width,height}; clamping is the gateway's job, the fake just stays
    inside the frame so it is always clamp-valid)."""
    rng = _rng_for("yolobbox", i, op_id)
    w, h = _FAKE_FRAME
    bw = rng.randint(24, 180)
    bh = rng.randint(24, 150)
    return {
        "x": rng.randint(0, w - bw),
        "y": rng.randint(0, h - bh),
        "width": bw,
        "height": bh,
    }


# (op_id, property-name) -> (kind, arg). Overrides consulted BEFORE generic
# generation; this is where the plan's shipped-correct bullets live:
#   * embedding: the light lane's 512-dim reid vector, L2-normalized, with
#     embedding_dimension pinned to the same width so the payload cannot
#     contradict its own declared dimension;
#   * inference_time_ms constants (never wall-clock; never processing_time_ms).
# "class" (the detection key, a pydantic alias over class_name) and the
# per-profile class vocabulary belong to the yolo LITERAL generators (their
# routes declare a bare dict, so there is no field list for the walker to
# consult); llm_slots' slot fields are pinned as a const for the same reason.
_OVERRIDES: dict[tuple[str, str], tuple[str, Any]] = {}
_OVERRIDES[("enrich_lt_person_reid", "embedding")] = ("unit_embedding", 512)
_OVERRIDES[("enrich_lt_person_reid", "embedding_dimension")] = ("const", 512)
# B2.2 (owner ruling 68): the fake's re-ID vectors carry a model ID that never
# matches a real one, so a gallery enrolled from real weights answers
# space_mismatch against the fake instead of scoring fake vectors. Real IDs are
# osnet_model_id()'s grammar, "osnet-ain-x1-0@<weights stem>@<sha256[:12]>".
FAKE_REID_MODEL_ID = "fake-ai-reid@deterministic@not-a-checkpoint"
_OVERRIDES[("enrich_lt_person_reid", "model_id")] = ("const", FAKE_REID_MODEL_ID)
# R8 S3 (2026-09-29, owner rulings 1 + 5) pruned every override entry keyed on
# a retired op id: clip_embed's 768-dim CLIP embedding, the six florence
# 4-coord bbox entries, florence_phrase_grounding's list-of-quads and
# florence_ocr_with_regions' 8-coord quad - and with them the florence_bbox /
# florence_bbox_list override KINDS and their _florence_bbox helper, since a
# generator no reachable override consults is dead code in a shipped package
# (the same "pointer at nothing" class providers.py refuses for
# _CLIENT_MODULES, one layer down). The shapes they pinned are not lost: the
# florence list-of-floats arity lesson - 4 coords everywhere, EIGHT on the
# OCR-region quad path, because a fake emitting 4 there trains consumers on
# the wrong arity - is stated in full by the tombstone tests that used to drive
# it (test_fake_provider, test_conformance_geometry G2/G3).
# Qualified keys ("<DefName>.<prop>", lookup falls back to the bare name,
# exact match wins) exist because florence_analyze_scene once carried BOTH
# caption regions (4-coord) and text_regions (8-coord quads) under one
# property name; A7.2 deleted that op and R8 S3 deleted the florence bbox
# entries above, but the MECHANISM stays - vlm_assess's response walks $defs
# (VlmCriterion / VlmProvenance) through _resolve, so def-qualification is
# still exercised on live surface.
# llm fixed bodies (shape comes from snapshots; values pinned here)
_OVERRIDES[("llm_completion", "content")] = ("const", "the quick brown fox")
_OVERRIDES[("llm_completion", "tokens_predicted")] = ("const", 9)
_OVERRIDES[("llm_chat_completion", "content")] = ("const", "a person walks a dog")
# llm_slots: the snapshot is array-of-free-form-object (llama.cpp /slots
# scrape, performance_collector.py:214 reads state + n_ctx) - the walker
# cannot invent faithful slot fields, so the value is pinned from the
# consumer's own expectations.
_OVERRIDES[("llm_slots", "llm_slots")] = (
    "const",
    [
        {"id": 0, "n_ctx": 4096, "n_ctx_seq": 512, "state": 1},
        {"id": 1, "n_ctx": 4096, "n_ctx_seq": 512, "state": 0},
    ],
)


# --- generic snapshot walker ----------------------------------------------


def _resolve(node: dict[str, Any], ctx: dict[str, Any]) -> tuple[dict[str, Any], str]:
    """Follow $ref chains; return (node, def_name). The def name qualifies
    property overrides so an op carrying TWO different bbox definitions
    (historically analyze_scene: CaptionedRegion 4-coord AND OCRRegion
    8-coord - A7.2 deleted that op; the qualification mechanism stays) can pin
    each - a bare-name match alone could not tell them apart."""
    def_name = ""
    while "$ref" in node:
        def_name = node["$ref"].rsplit("/", 1)[-1]
        node = ctx["defs"][def_name]
    return node, def_name


def _gen_value(  # noqa: PLR0911 - one return per JSON-Schema type is the shape of a type dispatcher
    node: dict[str, Any], name: str, ctx: dict[str, Any], i: int = 0, qual: str = ""
) -> Any:
    """Generate a schema-valid value for one property. Deterministic: every
    branch consumes only the (op_id, name, i) seed path carried in ctx."""
    op_id = ctx["op_id"]
    qualified = f"{qual}.{name}" if qual else name
    override = _OVERRIDES.get((op_id, qualified)) or _OVERRIDES.get((op_id, name))
    if override is not None:
        kind, arg = override
        if kind == "unit_embedding":
            return _unit_embedding(arg, op_id)
        if kind == "const":
            return arg
        raise ValueError(f"{op_id}: unknown override kind {kind}")
    node, def_name = _resolve(node, ctx)
    qual = def_name or qual
    if "anyOf" in node:
        # Deterministic branch choice: NULLABLE schemas here are genuinely
        # optional metadata (ensemble_metadata) - pick the non-null branch,
        # never the null one, so the fake exercises the populated shape.
        branches = [b for b in node["anyOf"] if b.get("type") != "null"] or node["anyOf"]
        return _gen_value(branches[0], name, ctx, i, qual)
    if "enum" in node:
        return node["enum"][0]
    t = node.get("type")
    if t == "number":
        if name == "inference_time_ms":
            return _FAKE_INFERENCE_MS
        if name == "total_inference_time_ms":
            return _FAKE_TOTAL_MS
        return round(_rng_for(op_id, qualified, i, "num").uniform(0.1, 0.9), 4)
    if t == "integer":
        return _rng_for(op_id, qualified, i, "int").randint(1, 8)
    if t == "boolean":
        return _rng_for(op_id, qualified, i, "bool").random() < 0.5
    if t == "string":
        return f"{name}_{_rng_for(op_id, qualified, i, 'str').randint(100, 999)}"
    if t == "array":
        return _gen_array(node, name, ctx, qual)
    if t == "object":
        if "properties" in node:
            return {k: _gen_value(v, k, ctx, 0, qual) for k, v in node["properties"].items()}
        # free-form object (scores/similarities/enrichments maps)
        rng = _rng_for(op_id, qualified, "free-obj")
        return {
            "alpha": round(rng.uniform(0.1, 0.9), 4),
            "bravo": round(rng.uniform(0.1, 0.9), 4),
        }
    raise ValueError(f"{op_id}: cannot generate value for schema {node!r} (name {name})")


def _gen_array(node: dict[str, Any], name: str, ctx: dict[str, Any], qual: str = "") -> list[Any]:
    items = node.get("items", {})
    item_type, _ = _resolve(items, ctx)
    count = 2 if item_type.get("type") != "string" else 1
    # minItems (e.g. a 4-coord bbox array) outranks the default 2 - a
    # shorter instance violates the snapshot we validate against.
    count = max(count, node.get("minItems") or 1)
    return [_gen_value(items, f"{name}.{i}", ctx, i, qual) for i in range(count)]


def generate_from_snapshot(op_id: str, profile: str = "gateway") -> dict[str, Any] | list[Any]:
    schema = snapshot_for(op_id)
    if schema is None:
        raise KeyError(f"{op_id} has no committed response snapshot - use the literal generator")
    ctx = {"op_id": op_id, "defs": schema.get("$defs", {}), "profile": profile}
    result = _gen_value(schema, op_id, ctx)
    if not isinstance(result, dict | list):
        raise TypeError(f"{op_id}: snapshot produced {type(result)}")
    return result


def create_response_bytes(obj: Any) -> bytes:
    """The ONE serializer. sort_keys + compact separators = the byte-identity
    mechanism; dict insertion order cannot leak, whitespace cannot vary."""
    return json.dumps(obj, sort_keys=True, separators=(",", ":")).encode("utf-8")


# --- literal generators for the GEN_GAPS ops ------------------------------
#
# GEN_GAPS (recorded in the WP8.2 ledger; each op DOES have a committed
# snapshot now - the generator extended to snapshot what WAS snapshotable -
# but the WALKER cannot produce faithful values for them, so they route here:
#   * yolo26_detect / yolo26_detect_batch / yolo26_segment: the routes
#     declare `-> dict[str, Any]` (no pydantic model); the committed
#     snapshot is the honest BARE dict (+ x-deployed-keys naming the WP7.4
#     shape). A walker over a bare dict emits {}-ish filler; the deployed
#     keys/values below are the pinned truth the whole suite consumes.
# R8 S3 retired the other four members (model_status, model_preload,
# model_unload, object_distance). Their half of the ledger entry read: "the
# committed snapshots come from the REAL server classes, AST-extracted from
# ai/enrichment/model.py by gen-ai-contract, and the literals below are
# validated against them - which proves the mirror." The sweep took the file,
# the mirror and the literals together; a literal with nothing to mirror is
# the decorative half of the shape the whole slice refuses to leave behind.
# Either way the response is still schema-VALIDATED against the committed
# snapshot - the schema-driven guarantee holds for every op in the registry.

_YOLO_DETECT_KEYS = ("detections", "image_width", "image_height", "inference_time_ms")


def _yolo_detection(i: int, op_id: str, profile: str) -> dict[str, Any]:
    return {
        "class": _class_name(profile, i, op_id),
        "confidence": _confidence(i, op_id),
        "bbox": _yolo_bbox_dict(i, op_id),
    }


def _literal_generate(op_id: str, payload: Any, profile: str) -> dict[str, Any]:  # noqa: ARG001 - payload stays in the signature: generate() passes it uniformly for every op, and the retired model_preload/unload literals were its consumers
    if op_id in ("yolo26_detect", "yolo26_segment"):
        w, h = _FAKE_FRAME
        return {
            "detections": [_yolo_detection(i, op_id, profile) for i in range(3)],
            "image_width": w,
            "image_height": h,
            "inference_time_ms": _FAKE_INFERENCE_MS,
        }
    if op_id == "yolo26_detect_batch":
        w, h = _FAKE_FRAME
        # Gateway batch item shape (adapters/yolo26.py:421-427): NO
        # per-item inference_time_ms; the total carries it.
        return {
            "results": [
                {
                    "detections": [_yolo_detection(i, op_id, profile)],
                    "image_width": w,
                    "image_height": h,
                }
                for i in range(2)
            ],
            "total_inference_time_ms": _FAKE_TOTAL_MS,
            "batch_size": 2,
        }
    raise KeyError(f"{op_id}: no snapshot and no literal generator")


_LITERAL_OPS = frozenset(
    {
        "yolo26_detect",
        "yolo26_detect_batch",
        "yolo26_segment",
        # R8 S3 retired the other four GEN_GAPS literals (model_status,
        # model_preload, model_unload, object_distance): their evidence file
        # ai/enrichment/model.py is swept, so the literals that mirrored its
        # pydantic classes field-for-field have nothing left to mirror.
    }
)


def generate(op_id: str, payload: Any = None, profile: str = "gateway") -> Any:
    """The one entry point: the GEN_GAPS ops route to the literal
    deployed-shape generator; the rest are WALKED from their committed
    snapshot. Both paths are schema-VALIDATED post-generation (validate()
    below) so the schema-driven guarantee holds for every op in the registry:
    a snapshot edit that makes the fake's output nonconformant reddens the
    suite either way."""
    value: Any
    if op_id in _LITERAL_OPS:
        value = _literal_generate(op_id, payload, profile)
    elif snapshot_for(op_id) is not None:
        value = generate_from_snapshot(op_id, profile)
    else:
        raise KeyError(f"{op_id}: no snapshot and not a literal op")
    if op_id == "vlm_assess" and isinstance(payload, dict):
        images = payload.get("image_paths")
        if isinstance(images, list) and images and all(isinstance(x, str) for x in images):
            # spec §3 Slots: "The FakeProvider returns a deterministic verdict
            # keyed on an image hash." The walk seeds op+profile only, so the
            # verdict fields are re-drawn from the image paths themselves -
            # same images replay identically (pure function of the parts),
            # different images can differ (the failure-ladder fixtures need
            # verdict variety). Keys are paths, never bytes (D10).
            rng = _rng_for(op_id, "|".join(images), profile, "verdict")
            value["verdict"] = rng.choice(["confirmed", "rejected", "uncertain"])
            value["risk_score"] = rng.randint(0, 100)
    validate(op_id, value)
    return value


def validate(op_id: str, value: Any) -> None:
    """Validate a generated response against the committed snapshot. The
    fake failing its OWN contract here is a loud bug, never a silent drift."""
    import jsonschema

    schema = snapshot_for(op_id)
    if schema is None:
        return
    jsonschema.validate(value, schema)
