"""The AI-tier contract (plan P, WP7.1): one importable package declaring
every AI operation the product surface has, generated from the DEPLOYED
surfaces.

ARCHITECTURE RULE (do not regress this): the backend must never import ai.* at
runtime. The AI servers ship in containers without the backend package, and
this dependency direction is exactly what made prompts.py:4381 a live
production crash (format_detections_with_quality importing the GPU service
module). operations.py and schemas/ under this package are GENERATED by
scripts/gen-ai-contract.py, which imports the adapter modules at GENERATION
TIME only - that is a drift gate, not a shared import. backend/tests/contracts/
ai_providers/test_ai_contract_registry.py enforces the rule on this package's
source.
"""

from backend.ai_contract.operations import CLIENT_METHODS, OPERATION_IDS, OPERATIONS
from backend.ai_contract.provider import Operation, ProviderId, availability_is_generated

__all__ = [
    "CLIENT_METHODS",
    "OPERATIONS",
    "OPERATION_IDS",
    "Operation",
    "ProviderId",
    "availability_is_generated",
]
