"""GENERATED by scripts/gen-ai-contract.py - DO NOT EDIT (edit surfaces or this generator, then re-run)

The 9-operation AI-tier registry (plan P WP7.1 generation;
regenerated by this script — the number is minted from the build,
not hand-edited). Availability
matrix slots: gateway / enrichment_light_adapter / per_model_server /
fake. The `fake` column is the WP8.2 conformance SPEC (FakeProvider
implements all 9), not a present-tense claim about code that exists.
"""

from __future__ import annotations

from backend.ai_contract.provider import Operation

OPERATIONS: dict[str, Operation] = {
    "enrich_lt_person_reid": Operation(
        id="enrich_lt_person_reid",
        method="POST",
        path="/enrich-lt/person-reid",
        availability={
            "gateway": True,
            "enrichment_light_adapter": True,
            "per_model_server": True,
            "fake": True,
        },
        client_methods=[],
        evidence="ai/gateway/adapters/enrichment_light.py:/person-reid mounted at /enrich-lt (ai/gateway/main.py:272-273)",
    ),
    "enrich_lt_threat_detect": Operation(
        id="enrich_lt_threat_detect",
        method="POST",
        path="/enrich-lt/threat-detect",
        availability={
            "gateway": True,
            "enrichment_light_adapter": True,
            "per_model_server": True,
            "fake": True,
        },
        client_methods=[],
        evidence="ai/gateway/adapters/enrichment_light.py:/threat-detect mounted at /enrich-lt (ai/gateway/main.py:272-273)",
    ),
    "llm_chat_completion": Operation(
        id="llm_chat_completion",
        method="POST",
        path="/v1/chat/completions",
        availability={
            "gateway": False,
            "enrichment_light_adapter": False,
            "per_model_server": True,
            "fake": True,
        },
        client_methods=[],
        evidence="ai/nemotron/model_hf.py:152,178,664",
    ),
    "llm_completion": Operation(
        id="llm_completion",
        method="POST",
        path="/completion",
        availability={
            "gateway": False,
            "enrichment_light_adapter": False,
            "per_model_server": True,
            "fake": True,
        },
        client_methods=[],
        evidence="backend/services/nemotron_analyzer.py:465; ai/nemotron/model_hf.py:618",
    ),
    "llm_slots": Operation(
        id="llm_slots",
        method="GET",
        path="/slots",
        availability={
            "gateway": False,
            "enrichment_light_adapter": False,
            "per_model_server": False,
            "fake": True,
        },
        client_methods=[],
        evidence="backend/services/performance_collector.py:220",
    ),
    "vlm_assess": Operation(
        id="vlm_assess",
        method="POST",
        path="/vlm/chat/completions",
        availability={
            "gateway": False,
            "enrichment_light_adapter": False,
            "per_model_server": True,
            "fake": True,
        },
        client_methods=["VlmClient.assess"],
        evidence="spec §3 (engine wire POST /v1/chat/completions, base64 image_url + json_schema); chat-shape enforcement probe proven ENFORCED at b7972 (scripts/vlm_probes/s2_multimodal_schema.py); schemas generated from backend/services/vlm_verdict.py classes",
    ),
    "yolo26_detect": Operation(
        id="yolo26_detect",
        method="POST",
        path="/yolo26/detect",
        availability={
            "gateway": True,
            "enrichment_light_adapter": False,
            "per_model_server": True,
            "fake": True,
        },
        client_methods=["DetectorClient.detect_objects"],
        evidence="ai/gateway/adapters/yolo26.py:/detect mounted at /yolo26 (ai/gateway/main.py:272-273)",
    ),
    "yolo26_detect_batch": Operation(
        id="yolo26_detect_batch",
        method="POST",
        path="/yolo26/detect/batch",
        availability={
            "gateway": True,
            "enrichment_light_adapter": False,
            "per_model_server": True,
            "fake": True,
        },
        client_methods=[],
        evidence="ai/gateway/adapters/yolo26.py:/detect/batch mounted at /yolo26 (ai/gateway/main.py:272-273)",
    ),
    "yolo26_segment": Operation(
        id="yolo26_segment",
        method="POST",
        path="/yolo26/segment",
        availability={
            "gateway": True,
            "enrichment_light_adapter": False,
            "per_model_server": False,
            "fake": True,
        },
        client_methods=[],
        evidence="ai/gateway/adapters/yolo26.py:/segment mounted at /yolo26 (ai/gateway/main.py:272-273)",
    ),
}

OPERATION_IDS: tuple[str, ...] = tuple(sorted(OPERATIONS))

CLIENT_METHODS: dict[str, str | None] = {
    "DetectorClient.detector_type": None,
    "DetectorClient.close": None,
    "DetectorClient.health_check": None,
    "DetectorClient.is_cold": None,
    "DetectorClient.get_warmth_state": None,
    "DetectorClient.model_readiness_probe": None,
    "DetectorClient.warmup": None,
    "DetectorClient.detect_objects": "yolo26_detect",
    "VlmClient.assess": "vlm_assess",
    "VlmClient.close": None,
    "VlmClient.wake": None,
    "VlmClient.prompt_text": None,
}
