"""Hand-written support types for the generated registry (WP7.1), plus the
declared provider interface (WP8.1).

Kept separate from operations.py because operations.py is generated and must
import its types from a STATIC sibling - generated code cannot import from
itself, and importing ai.* for the model classes would break the package's
no-ai-at-runtime rule. The PROVIDERS module at the bottom of this file
derives provider callables from operations.py + the backend clients, so the
import-time contract check needs no ai.* import either (the adapter surfaces
are already folded into the registry as data by scripts/gen-ai-contract.py).
"""

from __future__ import annotations

import inspect
from collections.abc import Callable
from dataclasses import dataclass, field
from enum import StrEnum
from typing import Any, Protocol, runtime_checkable


class ProviderId(StrEnum):
    """The provider slots the availability matrix speaks to.

    gateway / gateway-light / llamacpp-llm are deployed today; per-model-http
    is the native-host path (undeployed in prod compose); fake is the WP8.2
    conformance FakeProvider - declared so the matrix can state a CONFORMANCE
    SPEC (fake must implement all 38) rather than a present-tense fact.
    """

    GATEWAY = "gateway"
    GATEWAY_LIGHT = "gateway_light"
    PER_MODEL_HTTP = "per_model_http"
    LLAMACPP_LLM = "llamacpp_llm"
    FAKE = "fake"


# The four matrix slot keys operations.py emits. WP8.1 maps ProviderId ->
# slot; keeping the keys as data here means a rename updates one place.
MATRIX_SLOTS = ("gateway", "enrichment_light_adapter", "per_model_server", "fake")


@dataclass(frozen=True)
class Operation:
    id: str
    method: str
    path: str
    availability: dict[str, bool]
    # backend client methods mapped to this operation, "ClassName.method"
    client_methods: list[str]
    evidence: str


def availability_is_generated(module_source: str) -> bool:
    """True when a module's source carries the generator provenance header -
    the drift gate's contract, asserted by the registry tests rather than
    re-derived by hand."""
    return "GENERATED by scripts/gen-ai-contract.py" in module_source


def operations_for_slot(slot: str, ops: dict[str, Operation]) -> dict[str, Operation]:
    """The operations a given provider slot must satisfy. Raises on an
    unknown slot so a typo can't silently return {} and 'pass' a conformance
    run."""
    if slot not in MATRIX_SLOTS:
        raise KeyError(f"unknown matrix slot {slot!r}; known: {MATRIX_SLOTS}")
    return {op_id: op for op_id, op in ops.items() if op.availability.get(slot, False)}


# --- WP8.1: the declared provider interface -------------------------------
#
# The plan's thesis in code: the interface is BUILT FROM DEPLOYED SURFACES
# (the WP7.1 registry), not guessed. A provider registers a callable per
# declared operation; registration verifies each callable with
# inspect.signature BEFORE accepting it, and the whole registration is
# checked against the registry's availability matrix at import time.
#
# Why not repair AIServiceProtocol (the DECIDE, WP8.1): it claimed process()
# and get_metrics() that none of its three docstring-named implementers ever
# had (census 2026-09-19: DetectorClient/NemotronAnalyzer expose health_check
# only, EnrichmentClient neither), and nothing consumed it. Attribute
# presence - the only thing the old Protocol could ever check structurally -
# is exactly what rotted silently. It is removed, and this package's
# AIProvider is its successor: generated-registry-backed, signature-verified.


class ProviderContractError(RuntimeError):
    """Raised at registration when a provider's callable set violates the
    registry contract. Import-time failure by construction: PROVIDERS below
    registers at module import, and backend.ai_contract imports PROVIDERS.

    provider_id and operation_id are attributes so callers (and the Done-when
    test) can assert WHICH operation was named, not regex a message."""

    def __init__(self, provider_id: str, operation_id: str, reason: str) -> None:
        self.provider_id = provider_id
        self.operation_id = operation_id
        super().__init__(
            f"provider {provider_id!r} violates contract at {operation_id!r}: {reason}"
        )


@runtime_checkable
class AIProvider(Protocol):
    """Structural face of a registered provider.

    runtime_checkable presence (provider_id, operations) is a cheap identity
    check only. The conformance mechanism is register_provider's
    inspect.signature verification against the registry - the plan is
    explicit that presence alone is what let AIServiceProtocol rot, so this
    Protocol deliberately does not pretend to be the enforcement point.
    """

    provider_id: ProviderId

    def operations(self) -> dict[str, Callable[..., Any]]: ...


@dataclass(frozen=True)
class RegisteredProvider:
    """A provider accepted by register_provider: the verified callables plus
    the metadata the conformance suite (WP8.3) needs to drive them."""

    provider_id: ProviderId
    slot: str
    deployed: bool
    _ops: dict[str, Callable[..., Any]] = field(repr=False, default_factory=dict)

    def operations(self) -> dict[str, Callable[..., Any]]:
        """Return a copy so mutation cannot retroactively bypass the
        signature verification registration performed."""
        return dict(self._ops)


# ProviderId -> matrix slot. FAKE maps to the fake column, which is pure
# SPEC (all 38) until WP8.2 ships the fake app.
PROVIDER_SLOT: dict[ProviderId, str] = {
    ProviderId.GATEWAY: "gateway",
    ProviderId.GATEWAY_LIGHT: "enrichment_light_adapter",
    ProviderId.PER_MODEL_HTTP: "per_model_server",
    ProviderId.LLAMACPP_LLM: "per_model_server",
    ProviderId.FAKE: "fake",
}

_PROVIDERS: dict[str, RegisteredProvider] = {}


def _reject_uncallable_shape(op_id: str, fn: Any, provider_id: str) -> None:
    """Signature conformance the registry can actually verify for
    CLIENT-BOUND callables (the gateway ops ARE client methods, whose real
    signatures differ per operation - detect_objects takes
    (image_path, camera_id, session, ...), classify takes a payload-ish
    body). The enforceable contract:

      * inspect.signature() must resolve at all (a broken/foreign callable
        is caught here, not at first call);
      * no POSITIONAL_ONLY parameters: the WP8.3/WP8.4 conformance driver
        dispatches payload fields as keyword args - a positional-only
        client method cannot be driven through payload dispatch, so a
        refactor adding `/` silently un-drives the suite. This is the
        drift presence checks miss.

    The uniform fn(payload) shape itself belongs to the FakeProvider
    (WP8.2), which is written TO that shape; client-bound callables are
    driven through the clients' own dispatch, so payload-binding is not
    their contract."""
    try:
        sig = inspect.signature(fn)
    except (TypeError, ValueError) as exc:
        raise ProviderContractError(provider_id, op_id, f"inspect.signature failed: {exc}") from exc
    for name, param in sig.parameters.items():
        if param.kind is inspect.Parameter.POSITIONAL_ONLY:
            raise ProviderContractError(
                provider_id,
                op_id,
                f"parameter {name!r} is positional-only; payload dispatch "
                "binds keyword args and could not drive it",
            )


def register_provider(
    provider_id: ProviderId,
    ops: dict[str, Callable[..., Any]],
    registry: dict[str, Operation],
    *,
    deployed: bool = True,
    required: set[str] | None = None,
) -> RegisteredProvider:
    """Verify a provider's op->callable map against the registry, then store it.

    Fails (ProviderContractError, import-time by construction) when:
      - a callable's signature fails conformance (see
        _reject_uncallable_shape) or is not a coroutine function - every
        operation is an HTTP round trip, a sync def would block the event
        loop in real clients;
      - an op id is not in the registry, or the registry marks the slot
        unavailable for it;
      - the callable set does not EXACTLY equal `required` (default: the
        whole slot column) - both directions fail, and the error names the
        operation. `required` exists for SUBSET providers inside UNION
        slots: per_model_server is a column spanning every per-model app,
        so llamacpp-serve (one app) declares its derived subset. The slot
        check still forbids it from claiming ops its column marks False.
    """
    slot = PROVIDER_SLOT[provider_id]
    for op_id in sorted(ops):
        fn = ops[op_id]
        _reject_uncallable_shape(op_id, fn, provider_id.value)
        if not inspect.iscoroutinefunction(fn):
            raise ProviderContractError(
                provider_id.value,
                op_id,
                "not a coroutine function (every operation is an HTTP round trip)",
            )
    for op_id in sorted(ops):
        op = registry.get(op_id)
        if op is None:
            raise ProviderContractError(
                provider_id.value, op_id, "invented operation: not in the registry"
            )
        if not op.availability.get(slot, False):
            raise ProviderContractError(
                provider_id.value,
                op_id,
                f"registry marks slot {slot!r} unavailable for it",
            )
    if required is None:
        required = set(operations_for_slot(slot, registry))
    missing = required - set(ops)
    if missing:
        raise ProviderContractError(
            provider_id.value,
            sorted(missing)[0],
            f"declared operation missing from provider ({len(missing)} total: {sorted(missing)})",
        )
    extra = set(ops) - required
    if extra:
        raise ProviderContractError(
            provider_id.value,
            sorted(extra)[0],
            f"operation outside this provider's required set ({sorted(extra)})",
        )
    rec = RegisteredProvider(provider_id=provider_id, slot=slot, deployed=deployed, _ops=dict(ops))
    _PROVIDERS[provider_id.value] = rec
    return rec


def registered_providers() -> dict[str, RegisteredProvider]:
    """The providers registered so far - after importing backend.ai_contract
    this is the full live set (PROVIDERS runs at import; see that module)."""
    return dict(_PROVIDERS)
