"""Hand-written support types for the generated registry (WP7.1).

Kept separate from operations.py because operations.py is generated and must
import its types from a STATIC sibling - generated code cannot import from
itself, and importing ai.* for the model classes would break the package's
no-ai-at-runtime rule. WP8.1 builds the AIProvider Protocol on Operation.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum


class ProviderId(StrEnum):
    """The provider slots the availability matrix speaks to.

    gateway / gateway-light / llamacpp-llm are deployed today; per-model-http
    is the native-host path (undeployed in prod compose); fake is the WP8.2
    conformance FakeProvider - declared so the matrix can state a CONFORMANCE
    SPEC (fake must implement all 38) rather than a present-tense fact.
    """

    GATEWAY = "gateway"
    GATEWAY_LIGHT = "gateway_light"
    PER_MODEL_HTTP = "per_model_http"
    LLAMACPP_LLM = "llamacpp_llm"
    FAKE = "fake"


# The four matrix slot keys operations.py emits. WP8.1 maps ProviderId ->
# slot; keeping the keys as data here means a rename updates one place.
MATRIX_SLOTS = ("gateway", "enrichment_light_adapter", "per_model_server", "fake")


@dataclass(frozen=True)
class Operation:
    id: str
    method: str
    path: str
    availability: dict[str, bool]
    # backend client methods mapped to this operation, "ClassName.method"
    client_methods: list[str]
    evidence: str


def availability_is_generated(module_source: str) -> bool:
    """True when a module's source carries the generator provenance header -
    the drift gate's contract, asserted by the registry tests rather than
    re-derived by hand."""
    return "GENERATED by scripts/gen-ai-contract.py" in module_source


def operations_for_slot(slot: str, ops: dict[str, Operation]) -> dict[str, Operation]:
    """The operations a given provider slot must satisfy. Raises on an
    unknown slot so a typo can't silently return {} and 'pass' a conformance
    run."""
    if slot not in MATRIX_SLOTS:
        raise KeyError(f"unknown matrix slot {slot!r}; known: {MATRIX_SLOTS}")
    return {op_id: op for op_id, op in ops.items() if op.availability.get(slot, False)}
