#!/usr/bin/env python
"""Generate backend/ai_contract from the DEPLOYED AI surfaces (plan P, WP7.1).

Ground truth sources, in plan priority order:
  1. ai/gateway/adapters/*.py  - the deployed AI provider surface. Imported at
     GENERATION TIME only. The backend must never import ai.* at runtime (that
     inversion is what made prompts.py:4381 a live production crash); this
     script is a drift gate, not a shared import.
  2. The four backend client classes (DetectorClient, CLIPClient, FlorenceClient,
     EnrichmentClient - the plan's "six clients" counting the enrichment
     heavy/light split that one class fronts via config). Client-method ->
     operation mapping lives in CLIENT_OP_MAP below, evidence-cited.
  3. The llama.cpp / ai-llm wire shape (LLM_OPS below): the seven independent
     POST {llm_url}/completion sites, ai/nemotron/model_hf.py routes, and the
     llama.cpp-only /slots scrape. model_hf.py is NOT imported (torch/
     transformers at import time); its wire shape is transcribed with file:line
     evidence.
  4. PHANTOM_OPS: paths the backend calls that exist on NO gateway adapter -
     the WP7.3 Tier-A production 404s, declared here so the gap is
     machine-readable rather than folklore.

Usage:
    uv run python scripts/gen-ai-contract.py           # write backend/ai_contract
    uv run python scripts/gen-ai-contract.py --check   # CI drift gate (exit 1 +
                                                       # names every drifted file)
"""

from __future__ import annotations

import argparse
import difflib
import importlib
import inspect
import json
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
# `python scripts/gen-ai-contract.py` puts scripts/ (not the repo root) on
# sys.path[0]; the generation-time adapter imports need the root.
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))
PKG_DIR = REPO_ROOT / "backend" / "ai_contract"
SCHEMA_DIR = PKG_DIR / "schemas"

PROVENANCE = "GENERATED by scripts/gen-ai-contract.py - DO NOT EDIT (edit surfaces or this generator, then re-run)"

ADAPTER_MODULES = {
    "yolo26": "/yolo26",
    "clip": "/clip",
    "florence": "/florence",
    "enrichment": "/enrichment",
    "enrichment_light": "/enrich-lt",
}
# id prefixes deliberately differ from module names where the deployed prefix
# does (enrich-lt, not enrich_lt or enrichment-light): the wire is the contract.
ID_PREFIXES = {
    "yolo26": "yolo26",
    "clip": "clip",
    "florence": "florence",
    "enrichment": "enrichment",
    "enrichment_light": "enrich_lt",
}

INFRA_PATHS = {"/health", "/metrics", "/docs", "/redoc", "/openapi.json", "/"}


@dataclass(frozen=True)
class OperationStub:
    id: str
    method: str
    path: str


# --- non-gateway operations ------------------------------------------------
# Transcribed wire shapes for the LLM seam. Evidence is the generation-time
# fact base; --check reds when a surface moves without regeneration.
LLM_OPS: dict[str, dict[str, Any]] = {
    "llm_completion": {
        "method": "POST",
        "path": "/completion",
        "availability": {
            "gateway": False,
            "enrichment_light_adapter": False,
            # model_hf.py:618 @app.post("/completion") AND llama.cpp serve it
            "per_model_server": True,
            "fake": True,
        },
        "request": {
            "type": "object",
            "title": "LlmCompletionRequest",
            "description": (
                "Wire shape assembled independently at 7 backend sites "
                "(nemotron_analyzer.py:465,1046,3978; summary_generator.py:440; "
                "nemotron_streaming.py:99; prompt_service.py:938; "
                "pipeline_quality_audit_service.py:391; evaluation/harness.py:549). "
                "Consolidation is a recorded WP7.1 follow-on (decision: follow-on)."
            ),
            "properties": {
                "prompt": {"type": "string"},
                "n_predict": {"type": "integer"},
                "temperature": {"type": "number"},
                "stream": {"type": "boolean"},
            },
            "required": ["prompt"],
        },
        "response": {
            "type": "object",
            "title": "LlmCompletionResponse",
            "properties": {
                "content": {"type": "string"},
                "tokens_predicted": {"type": "integer"},
            },
        },
        "evidence": "backend/services/nemotron_analyzer.py:465; ai/nemotron/model_hf.py:618",
    },
    "llm_chat_completion": {
        "method": "POST",
        "path": "/v1/chat/completions",
        "availability": {
            # Tier C: llama.cpp serves /v1/completions (plural, OpenAI-compat);
            # model_hf.py:664 implements /v1/chat/completions. A non-llama.cpp
            # provider must declare which spelling it serves.
            "gateway": False,
            "enrichment_light_adapter": False,
            "per_model_server": True,
            "fake": True,
        },
        "request": {
            "type": "object",
            "title": "ChatCompletionRequest",
            "properties": {
                "messages": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "role": {"type": "string"},
                            "content": {"type": "string"},
                        },
                    },
                },
                "temperature": {"type": "number"},
                "max_tokens": {"type": "integer"},
            },
            "required": ["messages"],
        },
        "response": {
            "type": "object",
            "title": "ChatCompletionResponse",
            "properties": {
                "choices": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "message": {
                                "type": "object",
                                "properties": {"content": {"type": "string"}},
                            }
                        },
                    },
                }
            },
        },
        "evidence": "ai/nemotron/model_hf.py:152,178,664",
    },
    "llm_slots": {
        "method": "GET",
        "path": "/slots",
        "availability": {
            # Tier C: llama.cpp-only. Any provider #4 that is not llama.cpp
            # silently loses warmup + this metric unless it emulates the path.
            "gateway": False,
            "enrichment_light_adapter": False,
            "per_model_server": False,
            "fake": True,
        },
        "request": None,
        "response": {
            "type": "array",
            "title": "LlamaCppSlots",
            "items": {"type": "object"},
        },
        "evidence": "backend/services/performance_collector.py:214",
    },
}

# WP7.3 Tier A: the backend calls these; they 404 on the deployed gateway.
# per_model_server=True records where the path DOES exist (heavy server /
# native-host path); model_unload carries the path-shape divergence in its
# evidence so no reader mistakes the canonical path for the client's.
PHANTOM_OPS: dict[str, dict[str, Any]] = {
    "model_status": {
        "method": "GET",
        "path": "/models/status",
        "availability": {
            "gateway": False,
            "enrichment_light_adapter": False,
            "per_model_server": True,
            "fake": True,
        },
        "request": None,
        "response": None,
        "evidence": (
            "backend/services/enrichment_client.py:3257; "
            "backend/api/routes/model_management.py:186; "
            "grep over ai/gateway/adapters/ returns 0 hits (re-verified at "
            "generation time by check_phantoms)"
        ),
    },
    "model_preload": {
        "method": "POST",
        "path": "/models/preload",
        "availability": {
            "gateway": False,
            "enrichment_light_adapter": False,
            "per_model_server": True,
            "fake": True,
        },
        "request": None,
        "response": None,
        "evidence": (
            "backend/services/enrichment_client.py:3287; "
            "backend/api/routes/model_management.py:486,646"
        ),
    },
    "model_unload": {
        "method": "POST",
        "path": "/models/unload",
        "availability": {
            "gateway": False,
            "enrichment_light_adapter": False,
            # heavy server route: POST /models/unload?model_name=<name> (query)
            "per_model_server": True,
            "fake": True,
        },
        "request": None,
        "response": None,
        "evidence": (
            "canonical ai/enrichment/model.py:3552 (query-param model_name); "
            "backend posts /models/{name}/unload at model_management.py:560 - "
            "404 even against the real server (WP7.3 Tier A)"
        ),
    },
    "object_distance": {
        "method": "POST",
        "path": "/object-distance",
        "availability": {
            "gateway": False,
            "enrichment_light_adapter": False,
            # exists only on the undeployed native-host heavy server (Tier B)
            "per_model_server": True,
            "fake": True,
        },
        "request": None,
        "response": None,
        "evidence": (
            "backend/services/enrichment_client.py:1955 endpoint='object-distance'; "
            "0 gateway hits; zero non-test callers (WP7.3 deletion candidate)"
        ),
    },
}

# per-model-server availability for the 31 gateway ops. Evidence: the WP7.3
# gap table re-verified at draft time. /segment is gateway-only (yolo26
# server has no route: grep -c segment ai/yolo26/model.py == 0).
PER_MODEL_SERVER: dict[str, bool] = {
    "yolo26_detect": True,
    "yolo26_detect_batch": True,
    "yolo26_segment": False,
    "clip_embed": True,
    "clip_classify": True,
    "clip_similarity": True,
    "clip_batch_similarity": True,
    "clip_anomaly_score": True,
    "florence_extract": True,
    "florence_batch_extract": True,
    "florence_ocr": True,
    "florence_ocr_with_regions": True,
    "florence_detect": True,
    "florence_dense_caption": True,
    "florence_describe_region": True,
    "florence_phrase_grounding": True,
    "florence_detect_security_objects": True,
    "florence_analyze_scene": True,
    "enrichment_vehicle_classify": True,
    "enrichment_clothing_classify": True,
    "enrichment_demographics": True,
    "enrichment_action_classify": True,
    "enrichment_pet_classify": True,
    "enrichment_depth_estimate": True,
    "enrichment_pose_analyze": True,
    "enrichment_enrich": True,
    "enrich_lt_pose_analyze": True,
    "enrich_lt_threat_detect": True,
    "enrich_lt_person_reid": True,
    "enrich_lt_pet_classify": True,
    "enrich_lt_depth_estimate": True,
}

# Client method -> operation id (None = no HTTP AI call: lifecycle, health,
# circuit-breaker introspection). Keyed "ClassName.method". Derived from the
# four client classes' public surface (AST-dumped 2026-09-19).
CLIENT_OP_MAP: dict[str, str | None] = {
    # DetectorClient
    "DetectorClient.detector_type": None,
    "DetectorClient.close": None,
    "DetectorClient.health_check": None,
    "DetectorClient.is_cold": None,
    "DetectorClient.get_warmth_state": None,
    "DetectorClient.model_readiness_probe": None,
    "DetectorClient.warmup": None,
    "DetectorClient.detect_objects": "yolo26_detect",
    "DetectorClient.detect_objects_batch": "yolo26_detect_batch",
    "DetectorClient.segment_image": "yolo26_segment",
    # CLIPClient
    "CLIPClient.close": None,
    "CLIPClient.get_circuit_breaker_state": None,
    "CLIPClient.get_all_circuit_breaker_states": None,
    "CLIPClient.reset_circuit_breaker": None,
    "CLIPClient.check_health": None,
    "CLIPClient.embed": "clip_embed",
    "CLIPClient.anomaly_score": "clip_anomaly_score",
    "CLIPClient.classify": "clip_classify",
    "CLIPClient.similarity": "clip_similarity",
    "CLIPClient.batch_similarity": "clip_batch_similarity",
    # FlorenceClient
    "FlorenceClient.close": None,
    "FlorenceClient.get_circuit_breaker_state": None,
    "FlorenceClient.get_all_circuit_breaker_states": None,
    "FlorenceClient.reset_circuit_breaker": None,
    "FlorenceClient.check_health": None,
    "FlorenceClient.extract": "florence_extract",
    "FlorenceClient.batch_extract": "florence_batch_extract",
    "FlorenceClient.ocr": "florence_ocr",
    "FlorenceClient.ocr_with_regions": "florence_ocr_with_regions",
    "FlorenceClient.detect": "florence_detect",
    "FlorenceClient.dense_caption": "florence_dense_caption",
    "FlorenceClient.describe_regions": "florence_describe_region",
    "FlorenceClient.phrase_grounding": "florence_phrase_grounding",
    "FlorenceClient.detect_security_objects": "florence_detect_security_objects",
    # EnrichmentClient (fronts heavy /enrichment AND light /enrich-lt per config)
    "EnrichmentClient.close": None,
    "EnrichmentClient.get_circuit_breaker_state": None,
    "EnrichmentClient.get_all_circuit_breaker_states": None,
    "EnrichmentClient.is_circuit_open": None,
    "EnrichmentClient.reset_circuit_breaker": None,
    "EnrichmentClient.check_health": None,
    "EnrichmentClient.is_healthy": None,
    "EnrichmentClient.classify_vehicle": "enrichment_vehicle_classify",
    "EnrichmentClient.classify_pet": "enrichment_pet_classify",
    "EnrichmentClient.classify_clothing": "enrichment_clothing_classify",
    "EnrichmentClient.estimate_depth": "enrichment_depth_estimate",
    "EnrichmentClient.estimate_object_distance": "object_distance",
    "EnrichmentClient.analyze_pose": "enrichment_pose_analyze",
    "EnrichmentClient.classify_action": "enrichment_action_classify",
    "EnrichmentClient.detect_threats": "enrich_lt_threat_detect",
    "EnrichmentClient.analyze_demographics": "enrichment_demographics",
    "EnrichmentClient.compute_reid_embedding": "enrich_lt_person_reid",
    "EnrichmentClient.enrich_detection": "enrichment_enrich",
    "EnrichmentClient.get_model_status": "model_status",
    "EnrichmentClient.preload_model": "model_preload",
}


def normalize_client_path(raw: str) -> str:
    """Normalize a client-constructed URL fragment to a registry path.

    Handles the f-string/placeholder spellings seen in the clients
    (``{llm_url}/completion``, ``f'{base}/clip/embed'``). Path params
    (``/models/{name}/unload``) are PRESERVED - matching tolerates them, it
    does not erase them.
    """
    s = raw.strip().strip("'\"")
    if s.startswith("f"):
        s = s[1:].strip("'\"")
    if "://" in s:
        s = "/" + s.split("://", 1)[1].split("/", 1)[-1]
    # drop leading placeholder: anything up to the first '/'
    if s and not s.startswith("/"):
        s = s[s.find("/") :] if "/" in s else s
    return s or "/"


def match_client_path(raw: str, ops: dict[str, OperationStub]) -> str | None:
    """Find the operation a client URL hits; path params match positionally."""
    path = normalize_client_path(raw)
    for op in ops.values():
        if op.path == path:
            return op.id

        # A `{param}` segment on EITHER side matches an elided/extra segment:
        # client /models/{name}/unload ~ canonical /models/unload (WP7.3
        # Tier-A divergence; the mapping records the relation, it does not
        # pretend the spellings are identical).
        def _bare(segs: list[str]) -> list[str]:
            return [s for s in segs if not (s.startswith("{") and s.endswith("}"))]

        if _bare(path.split("/")) == _bare(op.path.split("/")):
            return op.id
    return None


def collect_gateway_operations() -> tuple[dict[str, dict[str, Any]], dict[str, str]]:
    """Import the five adapter modules (generation time) and pull the truth.

    Returns ({op_id: record}, {path: op_id}). Request/response models come
    from the FastAPI route objects themselves - no hand transcription.
    """
    # Generation-time import: conftest's triton block does not apply to a bare
    # script run; the adapters do not need it (verified 2026-09-19: all five
    # import clean with no GPU present). Any import failure is a HARD generator
    # error - the drift gate must notice a surface that stopped importing.
    ops: dict[str, dict[str, Any]] = {}
    path_index: dict[str, str] = {}
    for mod_name, prefix in ADAPTER_MODULES.items():
        module = importlib.import_module(f"ai.gateway.adapters.{mod_name}")
        for route in module.router.routes:
            methods = getattr(route, "methods", None)
            if not methods:
                continue
            http = sorted(methods - {"HEAD", "OPTIONS"})
            if not http or route.path in INFRA_PATHS:
                continue
            op_id = f"{ID_PREFIXES[mod_name]}_{route.path.lstrip('/').replace('/', '_').replace('-', '_')}"
            # Request model from the ENDPOINT SIGNATURE: route.body_field /
            # dependant.body_params exist but their .annotation is None on
            # this FastAPI/pydantic stack (probed 2026-09-19), so the only
            # reliable introspection point is the callable itself. UploadFile
            # params (multipart: yolo26 file routes) are recorded as a
            # multipart marker - there is no body JSON schema to snapshot.
            req_schema: dict[str, Any] | None = None
            multipart = False
            for param in inspect.signature(route.endpoint).parameters.values():
                ann = param.annotation
                name = getattr(ann, "__name__", "")
                if name == "UploadFile" or param.default.__class__.__name__ in {"File", "Form"}:
                    multipart = True
                elif isinstance(ann, type) and hasattr(ann, "model_json_schema"):
                    req_schema = ann.model_json_schema()
            resp_model = getattr(route, "response_model", None)
            resp_schema = None
            if isinstance(resp_model, type) and hasattr(resp_model, "model_json_schema"):
                # some routes declare response_model=dict (bare mapping) -
                # no schema to snapshot there, record the route, not a fake schema
                resp_schema = resp_model.model_json_schema()
            ops[op_id] = {
                "method": http[0],
                "path": f"{prefix}{route.path}",
                "availability": {
                    "gateway": True,
                    "enrichment_light_adapter": mod_name == "enrichment_light",
                    "per_model_server": PER_MODEL_SERVER.get(op_id, False),
                    "fake": True,
                },
                "request": req_schema
                if req_schema is not None
                else (
                    {
                        "type": "string",
                        "contentEncoding": "binary",
                        "title": "multipart-form-data",
                        "description": "multipart file upload (UploadFile), no JSON body",
                    }
                    if multipart
                    else None
                ),
                "response": resp_schema,
                "evidence": f"ai/gateway/adapters/{mod_name}.py:{route.path} mounted at {prefix} (ai/gateway/main.py:181-185)",
            }
            path_index[ops[op_id]["path"]] = op_id
    return ops, path_index


def check_phantoms(ops: dict[str, dict[str, Any]]) -> None:
    """Generation-time re-verify: phantom paths must still be absent from the
    gateway truth. If someone implements one, the generator must LOUDLY
    reclassify it rather than keep a stale false row."""
    for op_id, rec in PHANTOM_OPS.items():
        if any(o["path"] == rec["path"] for o in ops.values()):
            raise SystemExit(
                f"PHANTOM_RECLASSIFIED: {op_id} {rec['path']} now exists on the "
                "gateway - move it out of PHANTOM_OPS in the generator, then regenerate"
            )


def build_all() -> tuple[dict[str, dict[str, Any]], dict[str, str]]:
    ops, path_index = collect_gateway_operations()
    check_phantoms(ops)
    for op_id, rec in {**LLM_OPS, **PHANTOM_OPS}.items():
        if op_id in ops:
            raise SystemExit(f"id collision: {op_id} declared in two sources")
        ops[op_id] = rec
    # client-map sanity: every mapped op exists
    mapped = {v for v in CLIENT_OP_MAP.values() if v}
    missing = mapped - set(ops)
    if missing:
        raise SystemExit(f"CLIENT_OP_MAP references unknown ops: {sorted(missing)}")
    return ops, path_index


def _client_methods_for(op_id: str) -> list[str]:
    return sorted(k for k, v in CLIENT_OP_MAP.items() if v == op_id)


def _ruff_formatted(source: str) -> str:
    """Run generated Python through the repo's ruff formatter via stdin.

    WHY: pre-commit's ruff-format hook rewrites this file on every commit
    (single->double quotes, dict wrapping), which made the committed bytes
    differ from regenerated bytes - the drift gate reds with a pure-formatter
    diff (measured 2026-09-19). Emitting at the formatter's fixpoint makes
    generated == committed == hook-formatted, one byte-identical shape.
    """
    proc = subprocess.run(
        [sys.executable, "-m", "ruff", "format", "-"],
        input=source,
        capture_output=True,
        text=True,
        check=True,
    )
    return proc.stdout


def render_operations_module() -> str:
    ops, _ = build_all()
    lines = [
        f'"""{PROVENANCE}',
        "",
        "The 38-operation AI-tier registry (plan P WP7.1). Availability matrix",
        "slots: gateway / enrichment_light_adapter / per_model_server / fake.",
        "The `fake` column is the WP8.2 conformance SPEC (FakeProvider must",
        "implement all 38), not a present-tense claim about code that exists.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from backend.ai_contract.provider import Operation",
        "",
        "OPERATIONS: dict[str, Operation] = {",
    ]
    for op_id in sorted(ops):
        rec = ops[op_id]
        lines.append(f"    {op_id!r}: Operation(")
        lines.append(f"        id={op_id!r},")
        lines.append(f"        method={rec['method']!r},")
        lines.append(f"        path={rec['path']!r},")
        lines.append(f"        availability={rec['availability']!r},")
        lines.append(f"        client_methods={_client_methods_for(op_id)!r},")
        lines.append(f"        evidence={rec['evidence']!r},")
        lines.append("    ),")
    lines.append("}")
    lines.append("")
    lines.append("OPERATION_IDS: tuple[str, ...] = tuple(sorted(OPERATIONS))")
    lines.append("")
    lines.append("CLIENT_METHODS: dict[str, str | None] = " + repr(CLIENT_OP_MAP))
    lines.append("")
    return _ruff_formatted("\n".join(lines))


_PRINT_WIDTH = 100  # .prettierrc printWidth; mirrors-prettier hook inherits it


def _json_primitive(x: object) -> bool:
    return x is None or isinstance(x, (bool, int, float, str))


def _json_node(node: object, indent: int, suffix: str) -> str:
    """Serialize one node at prettier 3.x's JSON fixpoint (verified against the
    pre-commit hook's prettier 3.2.4 bytes: 36/36 schemas byte-identical).

    Prettier's JSON rules this implements (each probed against the hook):
    - objects always print one-key-per-line (2-space indent, keys sorted here
      because the generator sorts; prettier itself preserves source order);
    - a primitive-only array collapses to one line iff the collapsed line -
      INCLUDING the trailing comma the parent appends (the 100/101 boundary
      was probed) - fits printWidth, else expands one element per line;
    - arrays of objects always expand with each object on its own block;
    - strings use json.dumps default escaping (\\uXXXX), which is prettier's.

    Deliberately NOT a prettier shell-out: CI jobs that run --check have no
    guarantee of the hook's pinned prettier@3.2.4 (the sandbox additionally
    runs 3.9.7 locally - byte-identical on this corpus, zero drift), and a
    subprocess would make generation machine-dependent. The hook's rewrite IS
    the contract; the fixpoint test in scripts/test_gen_ai_contract.py shells
    out to the hook binary (skipping cleanly when absent) to prove this
    serializer and the hook agree on every emitted file.
    """
    pad = " " * indent
    pad_in = " " * (indent + 2)
    if isinstance(node, dict):
        if not node:
            raise ValueError("empty object (shape not verified against the hook)")
        keys = sorted(node)
        parts = [
            f"{pad_in}{json.dumps(k)}: "
            f"{_json_node(node[k], indent + 2, ',' if i < len(keys) - 1 else '')}"
            for i, k in enumerate(keys)
        ]
        return "{\n" + ",\n".join(parts) + "\n" + pad + "}"
    if isinstance(node, list):
        if not node:
            return "[]"
        if all(_json_primitive(e) for e in node):
            single = json.dumps(node)
            if len(pad) + len(single) + len(suffix) <= _PRINT_WIDTH:
                return single
        elif not all(isinstance(e, dict) and e for e in node):
            raise ValueError(
                "array mixes primitives with containers, or nests arrays/empties "
                "(shape not verified against the hook)"
            )
        parts = [
            pad_in + _json_node(e, indent + 2, "," if i < len(node) - 1 else "")
            for i, e in enumerate(node)
        ]
        return "[\n" + ",\n".join(parts) + "\n" + pad + "]"
    return json.dumps(node)


def prettier_canonical(model: dict) -> str:
    """JSON Schema model -> the exact bytes the prettier pre-commit hook keeps."""
    return _json_node(model, 0, "") + "\n"


def render_schemas() -> dict[str, str]:
    ops, _ = build_all()
    out: dict[str, str] = {}
    for op_id in sorted(ops):
        for side in ("request", "response"):
            model = ops[op_id][side]
            if model is None:
                continue
            name = f"{op_id}.{side}.json"
            try:
                out[name] = prettier_canonical(model)
            except ValueError as exc:
                raise SystemExit(f"gen-ai-contract: {name}: {exc}") from exc
    return out


# provider.py is HAND-WRITTEN and lives in the package; the generator never
# writes it. operations.py (generated) imports the frozen Operation dataclass
# from that static sibling, so the runtime never needs to import ai.* - the
# adapters are imported by THIS script at generation time only.


def _generated_files() -> dict[str, str]:
    files = {"operations.py": render_operations_module()}
    for name, payload in render_schemas().items():
        files[f"schemas/{name}"] = payload
    return files


def cmd_write() -> int:
    files = _generated_files()
    SCHEMA_DIR.mkdir(parents=True, exist_ok=True)
    for rel, content in files.items():
        (PKG_DIR / rel).write_text(content, encoding="utf-8")
    print(f"wrote {len(files)} files under {PKG_DIR.relative_to(REPO_ROOT)}")
    return 0


def cmd_check(root: Path) -> int:
    files = _generated_files()
    pkg = root / "backend" / "ai_contract"
    drift: list[str] = []
    for rel, content in files.items():
        target = pkg / rel
        if not target.exists():
            drift.append(f"{rel}: MISSING from the committed tree")
            continue
        if target.read_text(encoding="utf-8") != content:
            diff = "".join(
                difflib.unified_diff(
                    target.read_text(encoding="utf-8").splitlines(keepends=True),
                    content.splitlines(keepends=True),
                    fromfile=f"committed/{rel}",
                    tofile="regenerated",
                    n=1,
                )
            )
            drift.append(f"{rel}: DRIFT\n{diff[:2000]}")
    committed = (
        {p.relative_to(pkg).as_posix() for p in (pkg / "schemas").glob("*.json")}
        if (pkg / "schemas").exists()
        else set()
    )
    stale = committed - {rel for rel in files if rel.startswith("schemas/")}
    for rel in sorted(stale):
        drift.append(f"{rel}: STALE (no longer generated - delete it)")
    if drift:
        print("AI CONTRACT DRIFT - regenerate: uv run python scripts/gen-ai-contract.py")
        for d in drift:
            print(f"--- {d}")
        return 1
    print("AI contract is current (operations.py + schemas/ match the surfaces)")
    return 0


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument(
        "--check", action="store_true", help="drift gate: regenerate, diff, fail on drift"
    )
    ap.add_argument(
        "--root", type=Path, default=REPO_ROOT, help="tree root to check/write (tests use a copy)"
    )
    args = ap.parse_args(argv)
    if args.check:
        return cmd_check(args.root)
    return cmd_write()


if __name__ == "__main__":
    sys.exit(main())
