#!/bin/bash
# Generate self-signed SSL certificates for development
#
# This script creates a self-signed certificate suitable for local development.
# For production, use certificates from a trusted CA (Let's Encrypt, etc.)
#
# Usage:
#   ./scripts/generate-ssl-cert.sh              # Uses default ./ssl directory
#   ./scripts/generate-ssl-cert.sh /path/to/ssl # Custom output directory
#
# Output files:
#   - cert.pem: Self-signed certificate
#   - key.pem: Private key
#   - cert.csr: Certificate signing request (optional, for reference)

set -e

# Output directory (default: ./ssl relative to project root)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
SSL_DIR="${1:-$PROJECT_ROOT/ssl}"

# Certificate configuration
DAYS_VALID=365
KEY_SIZE=4096
COUNTRY="US"
STATE="Local"
LOCALITY="Development"
ORGANIZATION="Home Security Intelligence"
COMMON_NAME="localhost"

# Subject Alternative Names (SANs)
# Add any additional hostnames or IPs here
SANS="DNS:localhost,DNS:*.localhost,IP:127.0.0.1,IP:::1"

echo "=========================================="
echo "SSL Certificate Generator"
echo "=========================================="
echo ""
echo "Output directory: $SSL_DIR"
echo "Certificate validity: $DAYS_VALID days"
echo "Key size: $KEY_SIZE bits"
echo ""

# Create output directory
mkdir -p "$SSL_DIR"
chmod 700 "$SSL_DIR"

# Check if certificates already exist
if [ -f "$SSL_DIR/cert.pem" ] && [ -f "$SSL_DIR/key.pem" ]; then
    echo "WARNING: Certificates already exist in $SSL_DIR"
    read -p "Overwrite existing certificates? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Aborted. Existing certificates preserved."
        exit 0
    fi
fi

echo "Generating private key..."
openssl genrsa -out "$SSL_DIR/key.pem" "$KEY_SIZE" 2>/dev/null

echo "Generating certificate signing request..."
openssl req -new \
    -key "$SSL_DIR/key.pem" \
    -out "$SSL_DIR/cert.csr" \
    -subj "/C=$COUNTRY/ST=$STATE/L=$LOCALITY/O=$ORGANIZATION/CN=$COMMON_NAME" \
    2>/dev/null

echo "Generating self-signed certificate..."
# Create a temporary config file for SANs
TEMP_CONFIG=$(mktemp)
cat > "$TEMP_CONFIG" << EOF
[req]
default_bits = $KEY_SIZE
prompt = no
default_md = sha256
distinguished_name = dn
x509_extensions = v3_ca

[dn]
C = $COUNTRY
ST = $STATE
L = $LOCALITY
O = $ORGANIZATION
CN = $COMMON_NAME

[v3_ca]
subjectAltName = $SANS
basicConstraints = critical,CA:TRUE
keyUsage = critical, digitalSignature, keyEncipherment, keyCertSign
extendedKeyUsage = serverAuth, clientAuth
EOF

openssl x509 -req \
    -in "$SSL_DIR/cert.csr" \
    -signkey "$SSL_DIR/key.pem" \
    -out "$SSL_DIR/cert.pem" \
    -days "$DAYS_VALID" \
    -extfile "$TEMP_CONFIG" \
    -extensions v3_ca \
    2>/dev/null

rm -f "$TEMP_CONFIG"

# Set secure permissions
chmod 600 "$SSL_DIR/key.pem"
chmod 644 "$SSL_DIR/cert.pem"
chmod 644 "$SSL_DIR/cert.csr"

echo ""
echo "=========================================="
echo "Certificate generated successfully!"
echo "=========================================="
echo ""
echo "Files created:"
echo "  - $SSL_DIR/cert.pem (certificate)"
echo "  - $SSL_DIR/key.pem (private key)"
echo "  - $SSL_DIR/cert.csr (signing request)"
echo ""
echo "Certificate details:"
openssl x509 -in "$SSL_DIR/cert.pem" -noout -subject -dates
echo ""
echo "To enable HTTPS:"
echo "  1. Set SSL_ENABLED=true in your .env file"
echo "  2. Optionally set SSL_CERT_DIR=$SSL_DIR"
echo "  3. Restart the frontend container"
echo ""
echo "NOTE: This is a self-signed certificate for development only."
echo "      Browsers will show a security warning. For production,"
echo "      use certificates from a trusted CA (Let's Encrypt, etc.)"
echo ""

# Add ssl directory to .gitignore if not already present
GITIGNORE="$PROJECT_ROOT/.gitignore"
if [ -f "$GITIGNORE" ]; then
    if ! grep -q "^ssl/$" "$GITIGNORE" && ! grep -q "^/ssl/$" "$GITIGNORE"; then
        echo "" >> "$GITIGNORE"
        echo "# SSL certificates (generated by scripts/generate-ssl-cert.sh)" >> "$GITIGNORE"
        echo "ssl/" >> "$GITIGNORE"
        echo "Added ssl/ to .gitignore"
    fi
fi
