#!/usr/bin/env bash
# sandbox-dev.sh — one-command dev loop for this sandbox (arm64, no GPU, docker not podman).
#
#   ./scripts/sandbox-dev.sh          sync onto latest main + bring everything up
#   ./scripts/sandbox-dev.sh sync     rebase current branch onto github/main
#   ./scripts/sandbox-dev.sh up       start pg/redis containers + backend + frontend
#   ./scripts/sandbox-dev.sh down     stop backend/frontend + containers
#   ./scripts/sandbox-dev.sh restart  down + up (no sync)
#   ./scripts/sandbox-dev.sh seed     load mock dashboard data (events, cameras, …)
#   ./scripts/sandbox-dev.sh status   what's running, health summary
#   ./scripts/sandbox-dev.sh logs     tail both logs (Ctrl-C to stop)
#
# Why hybrid: GHCR images are amd64-only (this host is arm64), there is no GPU,
# and docker-compose.prod.yml expects a podman socket + host mounts that don't
# exist here. Postgres/redis run as containers; backend (uvicorn) and frontend
# (vite) run natively — the same shape CI uses minus the prebuilt images.
#
# NOTE: `origin` points at a host-local path unreachable from the sandbox;
# the live remote is `github` (added once by this script).

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
GITHUB_URL="https://github.com/mikesvoboda/nemotron-v3-home-security-intelligence"
GH_IMAGE="ghcr.io/mikesvoboda/nemotron-v3-home-security-intelligence"
ENV_FILE="$ROOT/.env"
PIDS="/tmp/sandbox-dev.pids"
BACKEND_LOG="/tmp/backend.log"
FRONTEND_LOG="/tmp/frontend.log"
API=http://localhost:8000
WEB=https://localhost:8444

# The sandbox has an HTTP proxy; never route local calls through it.
# -k: the frontend serves our self-signed cert.
NCURL=(curl -sk --noproxy '*' -m 10)

log() { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33mWARN:\033[0m %s\n' "$*"; }
die() { printf '\033[1;31mERROR:\033[0m %s\n' "$*" >&2; exit 1; }

# ---------------------------------------------------------------- git sync --

do_sync() {
  cd "$ROOT"
  git remote get-url github >/dev/null 2>&1 || {
    log "adding github remote"; git remote add github "$GITHUB_URL"; }
  log "fetching github/main"
  git fetch -q github main

  local behind ahead
  behind=$(git rev-list --count HEAD..github/main)
  ahead=$(git rev-list --count github/main..HEAD)

  if [ "$behind" -eq 0 ]; then
    log "branch already current with github/main"
  elif [ "$ahead" -eq 0 ]; then
    log "fast-forwarding to github/main ($behind commits)"
    git merge --ff-only -q github/main
  else
    # Unique commits: rebase them on top of main, tagged for recovery.
    local head_now tag
    head_now=$(git rev-parse HEAD)
    tag="safety/pre-sync-$(git rev-parse --short HEAD)"
    git tag -f "$tag" "$head_now"
    log "diverged: $ahead unique commit(s) onto main +$behind (safety tag: $tag)"
    # Rebase needs an identity even though it changes no patch content.
    git config user.name  >/dev/null 2>&1 || git config user.name  "mike svoboda"
    git config user.email >/dev/null 2>&1 || git config user.email "msvoboda@maui.localdomain"
    GIT_EDITOR=true git rebase github/main || {
      warn "rebase stopped — resolve and 'git rebase --continue', or 'git rebase --abort'"
      die "sync incomplete"
    }
  fi
  git status -sb | head -1
}

# ------------------------------------------------------------------ secrets --

ensure_env() {
  cd "$ROOT"
  if [ -f "$ENV_FILE" ]; then
    return 0
  fi
  log "creating .env (local sandbox values; gitignored)"
  local pp
  pp=$(openssl rand -base64 24 | tr -d '/+=' | head -c 24)
  cat > "$ENV_FILE" <<EOF
# Local sandbox dev environment — generated by scripts/sandbox-dev.sh
ENVIRONMENT=development
LOG_LEVEL=INFO
POSTGRES_PASSWORD=$pp
DATABASE_URL=postgresql+asyncpg://security:$pp@localhost:5432/security
REDIS_URL=redis://localhost:6379
FILE_WATCHER_ENABLED=false
# No GPU here: AI containers can't run. These flags keep the health monitor
# quiet and stop /ready from gating on pipeline workers.
AI_RESTART_ENABLED=false
READINESS_REQUIRE_PIPELINE_WORKERS=false
OTEL_ENABLED=false
USE_AI_GATEWAY=false
NEMOTRON_URL=http://localhost:8091
EOF
}

# --------------------------------------------------------------- containers --

ensure_pg_redis() {
  docker network inspect security-net >/dev/null 2>&1 || \
    docker network create security-net >/dev/null
  local pp
  pp=$(sed -n 's/^POSTGRES_PASSWORD=//p' "$ENV_FILE")

  # Named volume: 'down' rm -f's the container, and a NEW anonymous volume
  # would silently give an empty database on next 'up' (bit us once). Named
  # volumes survive container removal, so seeded state persists across restart.
  docker volume inspect sandbox-postgres-data >/dev/null 2>&1 || \
    docker volume create sandbox-postgres-data >/dev/null
  _ensure_container postgres \
    docker run -d --name postgres --network security-net \
      -e POSTGRES_USER=security -e POSTGRES_PASSWORD="$pp" -e POSTGRES_DB=security \
      -p 127.0.0.1:5432:5432 --tmpfs /tmp \
      -v sandbox-postgres-data:/var/lib/postgresql/data postgres:16-alpine
  _ensure_container redis \
    docker run -d --name redis --network security-net \
      -p 127.0.0.1:6379:6379 --tmpfs /tmp \
      redis:7.4-alpine3.21 redis-server --save ''
}

_ensure_container() {
  local name=$1; shift
  if docker ps --format '{{.Names}}' | grep -qx "$name"; then
    return 0
  fi
  if docker ps -a --format '{{.Names}}' | grep -qx "$name"; then
    # Recreated sandbox: same name may exist with an old password baked in.
    docker rm -f "$name" >/dev/null
  fi
  log "starting $name container"
  "$@" >/dev/null || die "failed to start $name"   # docker run pulls if needed
}

ensure_cv2() {
  # OpenCV needs system libs that aren't in the base sandbox image.
  (cd "$ROOT" && uv run -q python -c 'import cv2' >/dev/null 2>&1) && return 0
  log "installing cv2 system libraries"
  sudo -n apt-get install -y -qq --no-install-recommends \
    libxcb1 libgl1 libglib2.0-0t64 libgomp1 ffmpeg >/dev/null 2>&1 ||
    warn "apt install failed — backend may fail to import cv2"
}

# ----------------------------------------------------------------- processes --

stop_app() {
  local name=$1 pattern=$2 pid
  # Primary: the PID this script recorded (covers the whole setsid group start).
  if [ -f "$PIDS" ]; then
    pid=$(grep "^$name " "$PIDS" | awk '{print $2}') || true
    [ -n "${pid:-}" ] && kill "$pid" 2>/dev/null || true
  fi
  # Fallback for orphans from earlier runs: match by cmdline BUT exclude this
  # script's ancestor chain — a wrapper command that merely *mentions* the
  # pattern (e.g. `sh down && pgrep uvicorn`) puts it in the parent's cmdline,
  # and a naive pkill then kills the calling shell (exit 143/144).
  local anc=" $$" a=$$
  while a=$(awk '{print $4}' /proc/"$a"/stat 2>/dev/null) && [ "${a:-1}" != 1 ]; do
    anc="$anc $a"
  done
  # Signal the matched process's whole group (launcher + interpreter share the
  # setsid'd group; our own ancestors never do) so no orphan survives.
  # The backend's graceful shutdown can hang on AI-retry background tasks, so
  # escalate TERM -> grace -> KILL.
  local pgs=() p pgid
  for p in $(pgrep -f "$pattern" 2>/dev/null); do
    case "$anc" in *" $p "*) continue ;; esac
    pgid=$(awk '{print $5}' /proc/"$p"/stat 2>/dev/null) || continue
    pgs+=("$pgid")
    kill -TERM -"$pgid" 2>/dev/null || true
  done
  if [ ${#pgs[@]} -gt 0 ]; then
    sleep 5
    for pgid in "${pgs[@]}"; do
      kill -0 -"$pgid" 2>/dev/null && kill -KILL -"$pgid" 2>/dev/null || true
    done
  fi
  if [ -f "$PIDS" ]; then grep -v "^$name " "$PIDS" > "$PIDS.new" || true; mv "$PIDS.new" "$PIDS"; fi
}

start_backend() {
  stop_app backend '[u]vicorn backend.main'
  sleep 1
  log "starting backend (uvicorn :8000)"
  cd "$ROOT"
  mkdir -p backend/data/thumbnails backend/data/logs
  PYROSCOPE_ENABLED=false setsid nohup uv run uvicorn backend.main:app \
    --host 0.0.0.0 --port 8000 > "$BACKEND_LOG" 2>&1 < /dev/null &
  echo "backend $!" >> "$PIDS"
}

ensure_vite_wrapper() {
  # vite.config.ts hardcodes https:true but its auto-cert handshake fails here
  # (TLS alert 40). Serve HTTPS with our own self-signed cert instead — the
  # backend's session cookie carries the Secure flag (auth.py:58), and browsers
  # DROP Secure cookies received over plain HTTP: login would return 200 while
  # the session silently disappears, and the UI reports a failed login.
  # Wrapper + certs are untracked and git-excluded.
  local w="$ROOT/frontend/vite.config.sandbox.mts"
  local certs="$ROOT/frontend/.sandbox-certs"
  grep -q 'vite.config.sandbox.mts' "$ROOT/.git/info/exclude" 2>/dev/null || \
    echo '/frontend/vite.config.sandbox.mts' >> "$ROOT/.git/info/exclude"
  grep -q '.sandbox-certs' "$ROOT/.git/info/exclude" 2>/dev/null || \
    echo '/frontend/.sandbox-certs/' >> "$ROOT/.git/info/exclude"
  if [ ! -f "$certs/cert.pem" ]; then
    log "generating self-signed dev certificate"
    mkdir -p "$certs"
    openssl req -x509 -newkey rsa:2048 -nodes \
      -keyout "$certs/key.pem" -out "$certs/cert.pem" -days 825 \
      -subj "/CN=localhost" \
      -addext "subjectAltName=DNS:localhost,IP:127.0.0.1" 2>/dev/null
  fi
  [ -f "$w" ] && return 0
  log "creating frontend/vite.config.sandbox.mts (HTTPS dev server)"
  cat > "$w" <<'MJS'
// Sandbox-local dev config — NOT part of the repo (.git/info/exclude).
// Wraps the project's vite.config.ts and supplies an explicit self-signed
// certificate via .sandbox-certs/. Real HTTPS is required: the backend sets
// the session cookie with the Secure flag (backend/api/routes/auth.py:58) and
// browsers drop Secure cookies received over plain HTTP — login would return
// 200 while the session silently disappears.
import { defineConfig, mergeConfig } from 'vite';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import projectConfigFn from './vite.config';

const certDir = fileURLToPath(new URL('./.sandbox-certs', import.meta.url));

export default defineConfig(async (env) => {
  const base =
    typeof projectConfigFn === 'function' ? await projectConfigFn(env) : projectConfigFn;
  return mergeConfig(base, {
    server: {
      https: {
        key: readFileSync(`${certDir}/key.pem`),
        cert: readFileSync(`${certDir}/cert.pem`),
      },
    },
  });
});
MJS
}

start_frontend() {
  stop_app frontend '[v]ite'
  sleep 1
  cd "$ROOT/frontend"
  if [ ! -d node_modules ]; then
    log "npm install (first run — may take a minute)"
    npm install --no-audit --no-fund --silent
  fi
  ensure_vite_wrapper
  log "starting frontend (vite :8444, HTTPS, self-signed)"
  setsid nohup npx vite --config vite.config.sandbox.mts \
    > "$FRONTEND_LOG" 2>&1 < /dev/null &
  echo "frontend $!" >> "$PIDS"
}

# ------------------------------------------------------------------ verify --

wait_healthy() {
  local what=$1 url=$2 want=$3 tries=${4:-30} i
  for ((i = 1; i <= tries; i++)); do
    local code
    code=$("${NCURL[@]}" -o /dev/null -w '%{http_code}' "$url" 2>/dev/null) || code=000
    [ "$code" = "$want" ] && { log "$what: healthy"; return 0; }
    sleep 3
  done
  warn "$what: not healthy after $((tries * 3))s (got HTTP $code) — see log"
  return 1
}

do_up() {
  ensure_env
  ensure_pg_redis
  ensure_cv2
  start_backend
  start_frontend
  local ok=0
  wait_healthy backend "$API/api/system/health/ready" 200 30 || ok=1
  wait_healthy frontend "$WEB/" 200 20 || ok=1
  echo
  do_status
  [ $ok -eq 0 ] || return 1
  echo
  echo "Next: publish the port from your host to browse the dashboard:"
  echo "  sbx ports ${SANDBOX_NAME:-<sandbox-name>} --publish 8444:8444/tcp"
  echo "Then open https://localhost:8444 (accept the self-signed cert warning once)."
  echo "First visit needs admin registration (SetupGuard)."
}

do_seed() {
  # Offline mock dashboard data (scripts/sandbox-seed.py): cameras, events with
  # thumbnails from committed test fixtures, alerts, plate reads. The project's
  # own scripts/seed-events.py needs the GPU pipeline; this one doesn't.
  # Talks to postgres directly, so it also works with the backend stopped.
  # Idempotent: re-runs skip unless data was created; pass --clear to re-seed.
  (cd "$ROOT" && uv run python scripts/sandbox-seed.py "${@:2}")
}

do_down() {
  stop_app frontend '[v]ite'
  stop_app backend '[u]vicorn backend.main'
  docker rm -f postgres redis >/dev/null 2>&1 || true
  log "stopped"
}

do_status() {
  printf '%-10s %s\n' postgres "$(docker inspect -f '{{.State.Status}}' postgres 2>/dev/null || echo absent)"
  printf '%-10s %s\n' redis    "$(docker inspect -f '{{.State.Status}}' redis 2>/dev/null || echo absent)"
  local b f
  b=$("${NCURL[@]}" -o /dev/null -w '%{http_code}' "$API/api/system/health/ready" 2>/dev/null || echo 000)
  f=$("${NCURL[@]}" -o /dev/null -w '%{http_code}' "$WEB/" 2>/dev/null || echo 000)
  printf '%-10s HTTP %s  (%s)\n' backend "$b" "$API"
  printf '%-10s HTTP %s  (%s)\n' frontend "$f" "$WEB"
  "${NCURL[@]}" "$API/api/system/health" 2>/dev/null | python3 -c '
import sys, json
try:
    d = json.load(sys.stdin)
    s = d["services"]
    print("health:    db=%s redis=%s ai=%s (ai unhealthy is expected — no GPU)"
          % (s["database"]["status"], s["redis"]["status"], s["ai"]["status"]))
except Exception:
    print("health:    backend not responding")
'
}

# -------------------------------------------------------------------- main --

case "${1:-up}" in
  up)      do_up ;;
  sync)    do_sync ;;
  down)    do_down ;;
  restart) do_down; do_up ;;
  fresh)   do_sync; do_up; do_seed ;;
  seed)    do_seed "$@" ;;
  status)  do_status ;;
  logs)    tail -f "$BACKEND_LOG" "$FRONTEND_LOG" ;;
  *) die "usage: $0 [up|sync|down|restart|fresh|seed|status|logs]  (default: up)" ;;
esac
