"""Tests for scripts/gen-ai-contract.py (WP7.1 drift generator).

House convention: scripts carry an adjacent test_*.py exercising the pure
logic; the CI drift gate itself is `gen-ai-contract.py --check` wired next to
the other generate-*- --check steps. These tests import the script via
importlib from its path (scripts/ is not a package) and never hit the network
or a Triton server.
"""

from __future__ import annotations

import importlib.util
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPT = REPO_ROOT / "scripts" / "gen-ai-contract.py"


def _load():
    spec = importlib.util.spec_from_file_location("gen_ai_contract", SCRIPT)
    assert spec and spec.loader
    mod = importlib.util.module_from_spec(spec)
    # register BEFORE exec: dataclass string-annotation resolution looks the
    # defining module up in sys.modules (AttributeError on None otherwise)
    sys.modules["gen_ai_contract"] = mod
    spec.loader.exec_module(mod)
    return mod


gen = _load()


class TestPathNormalizer:
    def test_strips_base_url_placeholder(self):
        assert gen.normalize_client_path("{llm_url}/completion") == "/completion"

    def test_strips_settings_format_placeholder(self):
        assert gen.normalize_client_path("f'{base}/yolo26/detect'") == "/yolo26/detect"

    def test_preserves_path_params(self):
        # /models/{name}/unload keeps its param - matching must tolerate it
        assert gen.normalize_client_path("/models/{name}/unload") == "/models/{name}/unload"

    def test_rejects_non_path(self):
        assert gen.normalize_client_path("https://host/x") == "/x"


class TestClientMatcher:
    def test_exact_suffix_match(self):
        ops = {"clip_embed": gen.OperationStub(id="clip_embed", method="POST", path="/clip/embed")}
        assert gen.match_client_path("/clip/embed", ops) == "clip_embed"

    def test_param_path_matches_canonical(self):
        # client's /models/{name}/unload must find the canonical
        # /models/unload operation - the WP7.3 Tier-A divergence exists
        # precisely because these differ; the matcher's job is the mapping,
        # NOT pretending they are identical.
        ops = {
            "model_unload": gen.OperationStub(
                id="model_unload", method="POST", path="/models/unload"
            )
        }
        assert gen.match_client_path("/models/{name}/unload", ops) == "model_unload"

    def test_unmatchable_returns_none(self):
        assert gen.match_client_path("/nowhere", {}) is None


class TestEmissionDeterminism:
    def test_emitted_operations_is_stable(self):
        a = gen.render_operations_module()
        b = gen.render_operations_module()
        assert a == b, "generated module must be byte-stable (no dict-order/time drift)"

    def test_schemas_are_canonical_json(self):
        """Each emitted schema is byte-stable through its OWN canonicalizer:
        reparse + re-emit reproduces the bytes. The canonicalizer sorts keys
        and serializes deterministically, so this pins sorted-key content and
        the prettier-shape layout in one invariant (the old assertion pinned
        only json.dumps(indent=2, sort_keys=True) - bytes the prettier hook
        then rewrote, see test_rendered_schemas_are_prettier_fixpoint)."""
        schemas = gen.render_schemas()
        for name, payload in schemas.items():
            reparsed = json.loads(payload)
            assert payload == gen.prettier_canonical(reparsed), (
                f"{name}: committed schema bytes must be the sorted-canonical form"
            )

    def test_provenance_header(self):
        assert "GENERATED by scripts/gen-ai-contract.py" in gen.render_operations_module()

    def test_rendered_is_ruff_fixpoint(self):
        """Generated bytes == ruff-format(generated bytes): the pre-commit
        hook rewrites committed generated files, so emitting anywhere off
        the formatter's fixpoint makes --check red with a pure-formatter
        diff (the exact failure measured on 2026-09-19's first landing)."""
        src = gen.render_operations_module()
        assert gen._ruff_formatted(src) == src

    def test_rendered_schemas_are_prettier_fixpoint(self, tmp_path):
        """Artifact bytes == hook-prettier(artifact bytes) for EVERY generated
        JSON file - schemas AND the WP7.2 goldens (snapshots + payloads). The
        JSON prettier hook (mirrors-prettier + prettier@3.2.4, printWidth 100
        from .prettierrc) collapsed the generator's multi-line `required`
        arrays on the first commit attempt - the same class of failure as the
        ruff one above. prettier_canonical() implements the hook's rules
        (collapse a primitive-only or array-of-arrays value iff the line
        INCLUDING the parent's trailing comma fits printWidth; arrays of
        objects always expand) rather than shelling out, so THIS test is the
        agreement proof: it runs every emitted file through a real prettier -
        same shape as the hook invocation (.prettierrc resolves, so printWidth
        100 applies)."""
        candidates = [
            os.environ.get("PRETTIER_BIN"),
            str(REPO_ROOT / "frontend" / "node_modules" / ".bin" / "prettier"),
            shutil.which("prettier"),
        ]
        prettier = next((c for c in candidates if c and Path(c).exists()), None)
        if prettier is None:
            pytest.skip("no prettier on PATH (repo precedent: skip cleanly)")
        # Batch ONE prettier process (per-file invocations blow the test
        # timeout); .prettierrc is copied alongside so config resolves like
        # it does for the real hook invocation (printWidth 100 is the rule).
        payloads = {
            rel: content for rel, content in gen._generated_files().items() if rel.endswith(".json")
        }
        assert len(payloads) > 36, "goldens missing from _generated_files()"
        for rel, payload in payloads.items():
            target = tmp_path / rel
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(payload, encoding="utf-8")
        shutil.copy(REPO_ROOT / ".prettierrc", tmp_path / ".prettierrc")
        proc = subprocess.run(
            [prettier, "--write", "--no-color", *sorted(payloads)],
            capture_output=True,
            text=True,
            cwd=tmp_path,
            check=False,
        )
        assert proc.returncode == 0, f"prettier failed: {proc.stderr}"
        for rel, payload in payloads.items():
            after = (tmp_path / rel).read_text(encoding="utf-8")
            assert after == payload, (
                f"{rel}: emitted bytes are not the prettier fixpoint - "
                "the commit hook WILL rewrite the file (drift-gate red). "
                f"first difference: {_first_diff(payload, after)}"
            )


def _first_diff(a: str, b: str) -> str:
    for la, lb in zip(a.splitlines(), b.splitlines(), strict=False):
        if la != lb:
            return f"emitted={la!r} prettier={lb!r}"
    return f"line counts differ: {len(a.splitlines())} vs {len(b.splitlines())}"


class TestVlmContract:
    """Phase 1.1 - the vlm_assess seam (spec §3). The drift doctrine in code:
    the constrained schema the client sends and the shape the parser expects
    must be the SAME generated artifact, derived from VlmVerdict. E5 (the
    nvext defect) is what happens when they are maintained separately."""

    def _canon(self, obj):
        return json.dumps(obj, sort_keys=True)

    def test_vlm_assess_op_declared(self):
        ops, _ = gen.build_all()
        assert "vlm_assess" in ops, "spec §3: one capability op vlm_assess in VLM_OPS"
        rec = ops["vlm_assess"]
        assert rec["method"] == "POST"
        # registered path is /vlm/-prefixed: the real engine wire is
        # /v1/chat/completions, but llm_chat_completion owns that op.path and
        # the fake mounts one route per path (fake/app.py:88) - an unprefixed
        # vlm_assess would double-mount and validate the wrong body.
        assert rec["path"] == "/vlm/chat/completions"
        assert rec["availability"] == {
            "gateway": False,
            "enrichment_light_adapter": False,
            "per_model_server": True,
            # fake availability is the spec column; absent here the fake
            # under-declares and registration fails (provider.py:227-235)
            "fake": True,
        }

    def test_vlm_response_schema_derives_from_vlmverdict(self):
        """The generated op schema must equal the LIVE class's
        model_json_schema() - not a transcription, not a snapshot of itself."""
        from backend.services.vlm_verdict import VlmVerdict

        ops, _ = gen.build_all()
        assert self._canon(ops["vlm_assess"]["response"]) == self._canon(
            VlmVerdict.model_json_schema()
        ), "response schema drifted from VlmVerdict - regenerate, never hand-edit"

    def test_vlm_request_schema_derives_from_vlmassessrequest(self):
        from backend.services.vlm_verdict import VlmAssessRequest

        ops, _ = gen.build_all()
        assert self._canon(ops["vlm_assess"]["request"]) == self._canon(
            VlmAssessRequest.model_json_schema()
        )

    def test_vlm_goldens_generated(self):
        files = gen.render_goldens()
        assert "golden/snapshots/vlm_assess.response.snapshot.json" in files
        assert "golden/payloads/vlm_assess.response.example.json" in files
        assert "golden/snapshots/vlm_assess.request.snapshot.json" in files
        assert "golden/payloads/vlm_assess.request.example.json" in files
        # the payload golden is a fixture both sides import and the
        # conformance tier validates - an enum field must carry an ENUM
        # VALUE, not the "sample_<key>" default (the generator's _example_for
        # has no enum branch without this pin).
        payload = json.loads(files["golden/payloads/vlm_assess.response.example.json"])
        assert payload["verdict"] in {"confirmed", "rejected", "uncertain"}
        assert len(payload["criteria"]) >= 1
        assert 0 <= payload["risk_score"] <= 100

    def test_vlm_criteria_alias_the_shipped_verification_shape(self):
        """P0.4 shipped VerificationCriterion {name, passed, evidence} under a
        'VlmVerdict.criteria' docstring - the constrained model must stay an
        alias of that wire shape, not a fork of it."""
        from backend.api.schemas.event_verification import VerificationCriterion
        from backend.services.vlm_verdict import VlmCriterion

        assert set(VlmCriterion.model_fields) == set(VerificationCriterion.model_fields)

    def test_vlm_assess_context_tracks_the_frozen_assess_input(self):
        """VlmAssessContext repeats the frozen AssessInput's fields (kept
        separate so this module's import closure stays pydantic-only for the
        generator); a silent fork here would split the replay snapshot from
        the wire context - one code path, one shape (spec §2)."""
        from backend.evaluation.assess_input import AssessInput
        from backend.services.vlm_verdict import VlmAssessContext

        assert set(VlmAssessContext.model_fields) == set(AssessInput.model_fields)


class TestCheckMode:
    def test_check_passes_on_fresh_generation(self):
        """--check against the tree as committed exits 0 - if the committed
        operations.py/schemas drift from the surfaces, CI's step (and this
        test) go red naming the drifted file."""
        proc = subprocess.run(
            [sys.executable, str(SCRIPT), "--check"],
            capture_output=True,
            text=True,
            cwd=REPO_ROOT,
            check=False,
        )
        assert proc.returncode == 0, f"--check failed:\n{proc.stdout}\n{proc.stderr}"

    def test_check_detects_tampering(self, tmp_path):
        """Copy the package, mutate a committed schema, run --check with the
        tampered tree - must fail and NAME the file."""
        target = tmp_path / "backend" / "ai_contract"
        target.mkdir(parents=True)
        src = REPO_ROOT / "backend" / "ai_contract"
        if not (src / "operations.py").exists():
            pytest.skip("package not generated yet")
        shutil.copytree(src, target, dirs_exist_ok=True)
        schema_dir = target / "schemas"
        if not any(schema_dir.glob("*.json")):
            pytest.skip("no schemas emitted yet")
        victim = next(iter(schema_dir.glob("*.json")))
        victim.write_text(victim.read_text() + "\n// tampered\n")
        proc = subprocess.run(
            [sys.executable, str(SCRIPT), "--check", "--root", str(tmp_path)],
            capture_output=True,
            text=True,
            cwd=REPO_ROOT,
            check=False,
        )
        assert proc.returncode != 0
        assert victim.name in proc.stdout + proc.stderr, (
            "--check must NAME the drifted schema file in its failure output"
        )
