"""API schemas for request/response validation."""

from .ai_audit import (
    EnrichedSuggestion,
    ExampleImprovement,
)
from .alerts import (
    AlertCreate,
    AlertListResponse,
    AlertResponse,
    AlertRuleConditions,
    AlertRuleCreate,
    AlertRuleListResponse,
    AlertRuleResponse,
    AlertRuleUpdate,
    AlertSeverity,
    AlertStatus,
    AlertUpdate,
    DedupCheckRequest,
    DedupCheckResponse,
)
from .baseline import (
    ActivityBaselineEntry,
    ActivityBaselineResponse,
    AnomalyConfig,
    AnomalyConfigUpdate,
    AnomalyEvent,
    AnomalyListResponse,
    BaselineSummaryResponse,
    ClassBaselineEntry,
    ClassBaselineResponse,
    CurrentDeviation,
    DailyPattern,
    DeviationInterpretation,
    HourlyPattern,
    ObjectBaseline,
)
from .camera import CameraCreate, CameraListResponse, CameraResponse, CameraStatus, CameraUpdate
from .clips import (
    ClipGenerateRequest,
    ClipGenerateResponse,
    ClipInfoResponse,
    ClipStatus,
)
from .detections import (
    EnrichmentDataSchema,
    PersonEnrichmentData,
    PetEnrichmentData,
    VehicleEnrichmentData,
)
from .enrichment import (
    ClothingEnrichment,
    DepthEnrichment,
    EnrichmentResponse,
    EventEnrichmentsResponse,
    FaceEnrichment,
    ImageQualityEnrichment,
    LicensePlateEnrichment,
    PetEnrichment,
    PoseEnrichment,
    VehicleEnrichment,
    ViolenceEnrichment,
    WeatherEnrichment,
)
from .errors import (
    COMMON_ERROR_RESPONSES,
    ErrorCode,
    ErrorDetail,
    ErrorResponse,
    FlatErrorResponse,
    RateLimitErrorResponse,
    ServiceUnavailableResponse,
    ValidationErrorDetail,
    ValidationErrorResponse,
    raise_http_error,
)
from .health import (
    CheckResult,
    LivenessResponse,
    SimpleReadinessResponse,
)
from .health import (
    ReadinessResponse as HealthReadinessResponse,
)
from .llm_response import (
    LLMRawResponse,
    LLMRiskResponse,
)
from .llm_response import (
    RiskLevel as LLMRiskLevel,
)
from .notification import (
    DeliveryResultResponse,
    NotificationChannel,
    NotificationConfigResponse,
    NotificationDeliveryResponse,
    NotificationHistoryEntry,
    NotificationHistoryResponse,
    SendNotificationRequest,
    TestNotificationRequest,
    TestNotificationResponse,
)
from .scene_change import (
    SceneChangeAcknowledgeResponse,
    SceneChangeListResponse,
    SceneChangeResponse,
    SceneChangeType,
)
from .search import SearchRequest, SearchResponse, SearchResult
from .services import (
    CategorySummary,
    ContainerServiceStatus,
    ServiceActionResponse,
    ServiceCategory,
    ServiceInfo,
    ServicesResponse,
    ServiceStatusEvent,
)
from .websocket import (
    RiskLevel,
    WebSocketErrorCode,
    WebSocketErrorResponse,
    WebSocketEventData,
    WebSocketEventMessage,
    WebSocketMessage,
    WebSocketMessageType,
    WebSocketPingMessage,
    WebSocketPongResponse,
    WebSocketSceneChangeData,
    WebSocketSceneChangeMessage,
    WebSocketServiceStatus,
    WebSocketServiceStatusData,
    WebSocketServiceStatusMessage,
    WebSocketSubscribeMessage,
    WebSocketUnsubscribeMessage,
)
from .zone import ZoneCreate, ZoneListResponse, ZoneResponse, ZoneUpdate

__all__ = [
    # Constants (sorted separately)
    "COMMON_ERROR_RESPONSES",
    "ActivityBaselineEntry",
    "ActivityBaselineResponse",
    "AlertCreate",
    "AlertListResponse",
    "AlertResponse",
    "AlertRuleConditions",
    "AlertRuleCreate",
    "AlertRuleListResponse",
    "AlertRuleResponse",
    "AlertRuleUpdate",
    "AlertSeverity",
    "AlertStatus",
    "AlertUpdate",
    "AnomalyConfig",
    "AnomalyConfigUpdate",
    "AnomalyEvent",
    "AnomalyListResponse",
    "BaselineSummaryResponse",
    "CameraCreate",
    "CameraListResponse",
    "CameraResponse",
    "CameraStatus",
    "CameraUpdate",
    "CategorySummary",
    "CheckResult",
    "ClassBaselineEntry",
    "ClassBaselineResponse",
    "ClipGenerateRequest",
    "ClipGenerateResponse",
    "ClipInfoResponse",
    "ClipStatus",
    "ClothingEnrichment",
    "ContainerServiceStatus",
    "CurrentDeviation",
    "DailyPattern",
    "DedupCheckRequest",
    "DedupCheckResponse",
    "DeliveryResultResponse",
    "DepthEnrichment",
    "DeviationInterpretation",
    "EnrichedSuggestion",
    "EnrichmentDataSchema",
    "EnrichmentResponse",
    "ErrorCode",
    "ErrorDetail",
    "ErrorResponse",
    "EventEnrichmentsResponse",
    "ExampleImprovement",
    "FaceEnrichment",
    "FlatErrorResponse",
    "HealthReadinessResponse",
    "HourlyPattern",
    "ImageQualityEnrichment",
    "LLMRawResponse",
    "LLMRiskLevel",
    "LLMRiskResponse",
    "LicensePlateEnrichment",
    "LivenessResponse",
    "NotificationChannel",
    "NotificationConfigResponse",
    "NotificationDeliveryResponse",
    "NotificationHistoryEntry",
    "NotificationHistoryResponse",
    "ObjectBaseline",
    "PersonEnrichmentData",
    "PetEnrichment",
    "PetEnrichmentData",
    "PoseEnrichment",
    "RateLimitErrorResponse",
    "RiskLevel",
    "SceneChangeAcknowledgeResponse",
    "SceneChangeListResponse",
    "SceneChangeResponse",
    "SceneChangeType",
    "SearchRequest",
    "SearchResponse",
    "SearchResult",
    "SendNotificationRequest",
    "ServiceActionResponse",
    "ServiceCategory",
    "ServiceInfo",
    "ServiceStatusEvent",
    "ServiceUnavailableResponse",
    "ServicesResponse",
    "SimpleReadinessResponse",
    "TestNotificationRequest",
    "TestNotificationResponse",
    "ValidationErrorDetail",
    "ValidationErrorResponse",
    "VehicleEnrichment",
    "VehicleEnrichmentData",
    "ViolenceEnrichment",
    "WeatherEnrichment",
    "WebSocketErrorCode",
    "WebSocketErrorResponse",
    "WebSocketEventData",
    "WebSocketEventMessage",
    "WebSocketMessage",
    "WebSocketMessageType",
    "WebSocketPingMessage",
    "WebSocketPongResponse",
    "WebSocketSceneChangeData",
    "WebSocketSceneChangeMessage",
    "WebSocketServiceStatus",
    "WebSocketServiceStatusData",
    "WebSocketServiceStatusMessage",
    "WebSocketSubscribeMessage",
    "WebSocketUnsubscribeMessage",
    "ZoneCreate",
    "ZoneListResponse",
    "ZoneResponse",
    "ZoneUpdate",
    # Functions and utilities (sorted separately)
    "raise_http_error",
]
