"""API schemas for request/response validation."""

from .alerts import (
    AlertCreate,
    AlertListResponse,
    AlertResponse,
    AlertRuleConditions,
    AlertRuleCreate,
    AlertRuleListResponse,
    AlertRuleResponse,
    AlertRuleUpdate,
    AlertSeverity,
    AlertStatus,
    AlertUpdate,
    DedupCheckRequest,
    DedupCheckResponse,
)
from .camera import CameraCreate, CameraListResponse, CameraResponse, CameraUpdate
from .search import SearchRequest, SearchResponse, SearchResult
from .websocket import (
    WebSocketErrorCode,
    WebSocketErrorResponse,
    WebSocketMessage,
    WebSocketMessageType,
    WebSocketPingMessage,
    WebSocketPongResponse,
    WebSocketSubscribeMessage,
    WebSocketUnsubscribeMessage,
)
from .zone import ZoneCreate, ZoneListResponse, ZoneResponse, ZoneUpdate

__all__ = [
    "AlertCreate",
    "AlertListResponse",
    "AlertResponse",
    "AlertRuleConditions",
    "AlertRuleCreate",
    "AlertRuleListResponse",
    "AlertRuleResponse",
    "AlertRuleUpdate",
    "AlertSeverity",
    "AlertStatus",
    "AlertUpdate",
    "CameraCreate",
    "CameraListResponse",
    "CameraResponse",
    "CameraUpdate",
    "DedupCheckRequest",
    "DedupCheckResponse",
    "SearchRequest",
    "SearchResponse",
    "SearchResult",
    "WebSocketErrorCode",
    "WebSocketErrorResponse",
    "WebSocketMessage",
    "WebSocketMessageType",
    "WebSocketPingMessage",
    "WebSocketPongResponse",
    "WebSocketSubscribeMessage",
    "WebSocketUnsubscribeMessage",
    "ZoneCreate",
    "ZoneListResponse",
    "ZoneResponse",
    "ZoneUpdate",
]
