"""`verification` payload schema shared by Event REST + WebSocket (spec §4, P0.4).

One source of truth for the object shape - §3's drift doctrine applied to
this seam: the REST EventResponse and the WS event payload render THE SAME
object, so a frontend consumer branches on one shape. Keys are snake_case,
matching the repo's whole API surface (EventResponse's risk_score/
detection_count, WebSocketEventData's risk_score) - the ORM row's field
names pass through unchanged.

Presence semantics (spec §4, pinned by backend/tests/unit/services/
test_p04_verification_field.py): a legacy event has NO verification row, and
its payloads must stay byte-identical - so both consumers declare the field
with `exclude_if=lambda v: v is None`: the KEY IS ABSENT for legacy events,
present only when a row exists. Absent-not-null is the whole contract.
"""

from __future__ import annotations

from datetime import datetime
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

# spec §4 verdict enum; the ORM CHECK constraint mirrors this list
VerificationVerdict = Literal["confirmed", "rejected", "uncertain", "verification_failed"]


class VerificationCriterion(BaseModel):
    """One entry of the criteria checklist the VLM must satisfy (spec §3
    VlmVerdict.criteria / §6 post-validation: >= 1 criterion with evidence)."""

    name: str
    passed: bool
    evidence: str | None = None


class EventVerificationPayload(BaseModel):
    """The `verification` object on a verified event (spec §4).

    Rendered from an `EventVerification` row; `from_attributes` accepts the
    ORM row directly (field names are already identical).
    """

    model_config = ConfigDict(from_attributes=True)

    verdict: VerificationVerdict = Field(
        ...,
        description='Verification verdict: "confirmed", "rejected", "uncertain" '
        'or "verification_failed" (spec §4)',
    )
    scene_description: str | None = Field(
        None, description="Whole-scene description generated by the VLM"
    )
    criteria: list[VerificationCriterion] | None = Field(
        None, description="Criteria checklist: {name, passed, evidence}"
    )
    key_frame_detection_ids: list[int] | None = Field(
        None,
        description="Detection ids of the key frames the VLM reviewed "
        "(resolve to existing thumbnails, spec §4 event detail)",
    )
    engine: str = Field(..., description="Engine that produced the verdict (e.g. 'llama.cpp')")
    model_id: str = Field(..., description="Model id that produced the verdict")
    latency_ms: int | None = Field(
        None, description="Verifier call latency in ms; None = no timed call happened"
    )
    created_at: datetime | None = Field(
        None,
        description="When the verification ran (ISO 8601). Lax-typed on input: "
        "the REST path validates the ORM datetime, the WS path validates the "
        "ISO string a producer sends; both render ISO.",
    )


def verification_payload(event: object | None) -> EventVerificationPayload | None:
    """Render the verification object for an Event ORM row, reading the
    eagerly-loaded Event.verifications relationship (selectin). The newest
    row wins should a repair path ever stack rows; legacy events resolve to
    None, which both schemas then EXCLUDE from the payload entirely.

    The isinstance guard is deliberate: mocked events in unit tests carry
    MagicMock attributes, which are truthy but not row collections - a
    defensive read means only a real relationship ever produces a payload.
    """
    rows = getattr(event, "verifications", None) if event is not None else None
    if not isinstance(rows, (list, tuple)) or not rows:
        return None
    return EventVerificationPayload.model_validate(max(rows, key=lambda r: (r.created_at, r.id)))
