# Archived 2026-09-22 (gateway-consolidation follow-up) from setup.py @ 5d2ed562.
#
# generate_docker_override_content() emitted a docker-compose.override.yml, but
# setup.py stopped generating one: write_config_files() documents "No
# docker-compose.override.yml is generated" — .env is the sole source of truth
# and docker-compose.prod.yml reads all config from it. Nothing in the live tree
# called this function. Its service_configs table also targets containers the
# gateway consolidation retired (ai-yolo26, ai-florence, ai-clip,
# ai-enrichment — docker-compose.prod.yml now has only ai-llm, ai-llm-vllm and
# ai-gateway) and pins pre-consolidation host ports (frontend 5173/8443).
#
# Known stale consumer: archive/test_setup.py:15 imports it from `setup` at
# module level, so that archived test now raises ImportError if ever executed.
# It is outside pytest testpaths and never runs in CI; per the pass-2 ruling the
# whole archive/ tree is frozen (not linted/parsed) and awaits the owner's
# "wire into testpaths or delete?" call on the test_setup*.py row in
# archive/README.md — do not resurrect this snippet to make that test pass
# without that ruling.
#
# Body below is verbatim from git show HEAD:setup.py (lines 529-587 at
# deletion time); the only addition is the datetime import it needs.
from datetime import datetime


def generate_docker_override_content(config: dict) -> str:
    """Generate docker-compose.override.yml content.

    Args:
        config: Dictionary containing foscam_base_path, ai_models_path, and ports dict

    Returns:
        String content for docker-compose.override.yml file
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    ports = config.get("ports", {})
    foscam_base_path = config.get("foscam_base_path", "/export/foscam")

    lines = [
        f"# Generated by setup.py on {timestamp}",
        "# This file is auto-merged with docker-compose.prod.yml",
        "",
        "services:",
    ]

    service_configs = {
        "postgres": {"port": ports.get("postgres", 5432), "internal": 5432},
        "redis": {"port": ports.get("redis", 6379), "internal": 6379},
        "backend": {
            "port": ports.get("backend", 8000),
            "internal": 8000,
            "volumes": [f"{foscam_base_path}:/cameras:ro"],
        },
        "ai-yolo26": {"port": ports.get("yolo26", 8095), "internal": 8095},
        "ai-llm": {"port": ports.get("nemotron", 8091), "internal": 8091},
        "ai-florence": {"port": ports.get("florence", 8092), "internal": 8092},
        "ai-clip": {"port": ports.get("clip", 8093), "internal": 8093},
        "ai-enrichment": {"port": ports.get("enrichment", 8094), "internal": 8094},
        "frontend": {
            "port": ports.get("frontend", 5173),
            "internal": 80,
            "extra_ports": [(ports.get("frontend_https", 8443), 8443)],
        },
        "grafana": {"port": ports.get("grafana", 3002), "internal": 3000},
        "prometheus": {"port": ports.get("prometheus", 9090), "internal": 9090},
        "alertmanager": {"port": ports.get("alertmanager", 3000), "internal": 9093},
        "redis-exporter": {"port": ports.get("redis_exporter", 9121), "internal": 9121},
        "json-exporter": {"port": ports.get("json_exporter", 7979), "internal": 7979},
    }

    for service, cfg in service_configs.items():
        lines.append(f"  {service}:")
        lines.append("    ports:")
        lines.append(f'      - "{cfg["port"]}:{cfg["internal"]}"')
        if "extra_ports" in cfg:
            for host_port, container_port in cfg["extra_ports"]:
                lines.append(f'      - "{host_port}:{container_port}"')
        if "volumes" in cfg:
            lines.append("    volumes:")
            for vol in cfg["volumes"]:
                lines.append(f"      - {vol}")
        lines.append("")

    return "\n".join(lines)
